# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_vhdl -library xil_defaultlib {
  G:/_AN2_SEM2/CA/Laboratory/project_2/project_2.srcs/sources_1/imports/project_2/Bloc_Registri.vhd
  G:/_AN2_SEM2/CA/Laboratory/project_2/project_2.srcs/sources_1/imports/project_2/U_MEM.vhd
  G:/_AN2_SEM2/CA/Laboratory/project_2/project_2.srcs/sources_1/imports/project_2/U_EX.vhd
  G:/_AN2_SEM2/CA/Laboratory/project_2/project_2.srcs/sources_1/imports/project_2/U_control.vhd
  G:/_AN2_SEM2/CA/Laboratory/project_2/project_2.srcs/sources_1/imports/project_2/MPG.vhd
  G:/_AN2_SEM2/CA/Laboratory/project_2/project_2.srcs/sources_1/imports/project_2/I_decode.vhd
  G:/_AN2_SEM2/CA/Laboratory/project_2/project_2.srcs/sources_1/imports/project_2/Instruction_Fetch.vhd
  G:/_AN2_SEM2/CA/Laboratory/project_2/project_2.srcs/sources_1/imports/project_2/afisor.vhd
  G:/_AN2_SEM2/CA/Laboratory/project_2/project_2.srcs/sources_1/imports/project_2/test_env.vhd
}
read_xdc G:/_AN2_SEM2/CA/Laboratory/project_2/project_2.srcs/constrs_1/new/basys3.xdc
set_property used_in_implementation false [get_files G:/_AN2_SEM2/CA/Laboratory/project_2/project_2.srcs/constrs_1/new/basys3.xdc]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir G:/_AN2_SEM2/CA/Laboratory/project_2/project_2.cache/wt [current_project]
set_property parent.project_dir G:/_AN2_SEM2/CA/Laboratory/project_2 [current_project]
catch { write_hwdef -file MIPS16.hwdef }
synth_design -top MIPS16 -part xc7a35tcpg236-1
write_checkpoint MIPS16.dcp
report_utilization -file MIPS16_utilization_synth.rpt -pb MIPS16_utilization_synth.pb
