/*******************************************************************
* Name: processor_top.v
* Created: 29/9/2003 @ 15:50
* Description: this file contains the top level module
* Generated by: Handel-C Hardware Compiler, version 3.2.2710
* Chip family: AlteraCyclone
* Output style: Generic
*
* File structure:
*
* ¬processor_top.v
*   +proc_hcc.v
*******************************************************************/

// this is the top level module
module processor_top ( P1, inp, outp, rst );
  // interface description
  input P1;
  input [31:0] inp;
  output [31:0] outp;
  input rst;
  // Power cable
  wire [0:0] globals_PWR;
  // Ground cable
  wire [0:0] globals_GND;
  // global connection
  wire [0:0] globals_clock;
  // global connection
  wire [0:0] globals_True;
  // global connection
  wire [0:0] globals_CForkIn;
  // global connection
  wire [31:0] globals_value_Out;

  // root group
    // group netlist root
      // Power cable
      assign globals_PWR = 1'b1;
      // Ground cable
      assign globals_GND = 1'b0;
      // global connection
      assign outp = globals_value_Out;
    // end of group netlist root

    // Instantiation
    proc_hcc Instance0 (
      .globals_CForkIn_out(globals_CForkIn),
      .globals_GND(globals_GND),
      .globals_P1(P1),
      .globals_PWR(globals_PWR),
      .globals_True_out(globals_True),
      .globals_clock_out(globals_clock),
      .globals_inp(inp),
      .globals_rst(rst),
      .globals_value_Out_out(globals_value_Out)
    );
  // end of root group


endmodule

