LIBRARY IEEE;
USE ieee.STD_LOGIC_1164.ALL;

ENTITY CITIRE_ADRESA IS
	PORT(A:IN STD_LOGIC_VECTOR(7 DOWNTO 0);
	CLK:IN STD_LOGIC;
	ADR:OUT STD_LOGIC_VECTOR(3 DOWNTO 0)); 
end CITIRE_ADRESA;

ARCHITECTURE ARCH_CITIRE_ADRESA OF CITIRE_ADRESA IS
BEGIN
	PROCESS(CLK)
	VARIABLE INTER:STD_LOGIC_VECTOR(3 DOWNTO 0):="UUUU";
	BEGIN	   
		IF (CLK='1') AND (CLK'EVENT) THEN
			INTER:=A(3 DOWNTO 0);  
			ADR<=INTER;
		END IF;	
	END PROCESS;
END ARCH_CITIRE_ADRESA;	
		
		
		