--* This automatically generated file is part of WAVES testbench.
--*   This file was generated by Active-VHDL 3.0 (TB_generator v.1.0).
--*   Copyright (C) ALDEC Inc.
--* This VHDL file contains the declaration of DESIGN_DECLARATION package,
--* and is a part of WAVES Tesbench for entity "counter"
--* This file was generated on: Mon Mar  2 12:06:59 1998

--The DESIGN_DECLARATION package contains design specific declarations used in Testbench.
library IEEE;
use IEEE.std_logic_1164.all;
use STD.TEXTIO.all;
use IEEE.STD_LOGIC_TEXTIO.all;
use IEEE.waves_interface.all;
USE WORK.UUT_test_pins.all;

package DESIGN_DECLARATIONS is
	-- UUT ports name strings
	constant clk_NAME : STRING := "clk";
	constant reset_NAME : STRING := "reset";
	constant enable_NAME : STRING := "enable";
	constant load_NAME : STRING := "load";
	constant d_NAME : STRING := "d";
	constant q_NAME : STRING := "q";
	--Report file name declaration
	file REP_FILE : TEXT open WRITE_MODE is "$DSN\src\WAVES\counter_report.log";
	-- Test vectors file name declaration.
	file VECTOR_FILE : TEXT open READ_MODE is "$DSN\src\WAVES\Functional.vec";
	-- WGP (WAVE Generator Procedure) declarations
	type WND_TAGS is (START_T, END_T);
	type WND_TIMES is array (TEST_PINS, WND_TAGS) of EVENT_TIME;

	-- Constants declared below set the COMPARE WINDOW parameters.
	-- User can modified these values.
	constant WND_BEGIN_DEFAULT: EVENT_TIME := 1 ps;
	constant WND_END_DEFAULT: EVENT_TIME := 0 ps;

	-- Constant declared below sets the STIMULUS FRAME parameters.
	-- User can modified these values.
	constant STIM_BEGIN_DEFAULT: EVENT_TIME := 0 ns;

	-- Constant declared below defines the STIMULUS FRAMEs and COMPARE WINDOWs
	-- for all UUT ports present in test vector file.
	constant WINDOW_TIME_LIST: WND_TIMES := (
		clk => (START_T => STIM_BEGIN_DEFAULT, END_T => WND_END_DEFAULT),
		reset => (START_T => STIM_BEGIN_DEFAULT, END_T => WND_END_DEFAULT),
		enable => (START_T => STIM_BEGIN_DEFAULT, END_T => WND_END_DEFAULT),
		load => (START_T => STIM_BEGIN_DEFAULT, END_T => WND_END_DEFAULT),
		d_0 => (START_T => STIM_BEGIN_DEFAULT, END_T => WND_END_DEFAULT),
		d_1 => (START_T => STIM_BEGIN_DEFAULT, END_T => WND_END_DEFAULT),
		d_2 => (START_T => STIM_BEGIN_DEFAULT, END_T => WND_END_DEFAULT),
		d_3 => (START_T => STIM_BEGIN_DEFAULT, END_T => WND_END_DEFAULT),
		q_0 => (START_T => WND_BEGIN_DEFAULT, END_T => WND_END_DEFAULT),
		q_1 => (START_T => WND_BEGIN_DEFAULT, END_T => WND_END_DEFAULT),
		q_2 => (START_T => WND_BEGIN_DEFAULT, END_T => WND_END_DEFAULT),
		q_3 => (START_T => WND_BEGIN_DEFAULT, END_T => WND_END_DEFAULT));

	procedure CLOSE_VECTOR;
	procedure CLOSE_REPORT;

end DESIGN_DECLARATIONS;

package  body DESIGN_DECLARATIONS is
	procedure CLOSE_VECTOR is
	begin

	file_close (VECTOR_FILE);
	end;

	procedure CLOSE_REPORT is
	begin

	file_close (REP_FILE);
	end;
end package body;

