--* This automatically generated file is part of WAVES testbench.
--*   This file was generated by Active-VHDL 3.0 (TB_generator v.1.0).
--*   Copyright (C) ALDEC Inc.
--* This VHDL file contains the declaration of the Timing configuration of the Test Bench,
--* and is a part of WAVES Tesbench for entity "counter"
--* This file was generated on: Mon Mar  2 12:06:59 1998
configuration TIMING_FOR_counter of counter_wb is
	for TB_ARCHITECTURE
		for UUT : counter
			--
			-- The user should replace :
			-- ENTITY_NAME with an entity name from a backannotated VHDL file,
			-- ARCH_NAME   with an architecture name from a backannotated VHDL file,
			-- and uncomment the line below
			use entity work.counter (structure);
			--
		end for;
	end for;
end TIMING_FOR_counter;

