LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

ENTITY CITIRE_OP_CHITANTA IS
	PORT(A:IN STD_LOGIC_VECTOR(7 DOWNTO 0); --8 COMUTAROARE
	CLK,ENABLE:IN STD_LOGIC;
	OPERATIE,CHITANTA:OUT STD_LOGIC); --OPERATIA ESTE PRIMA 
END CITIRE_OP_CHITANTA;

ARCHITECTURE ARCH_CITIRE_OP_CHITANTA OF CITIRE_OP_CHITANTA IS
BEGIN
	PROCESS(CLK,ENABLE)
	VARIABLE INTER1,INTER2:STD_LOGIC:='U';
	BEGIN	   
		IF ENABLE='1' THEN
			OPERATIE<='U';
			CHITANTA<='U';
		ELSIF (CLK='1') AND (CLK'EVENT) THEN
			INTER1:=A(1);
			INTER2:=A(0);
			OPERATIE<=INTER1;
			CHITANTA<=INTER2;
		END IF;		
	END PROCESS;
END ARCH_CITIRE_OP_CHITANTA;	