LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;   

ENTITY COMP_EGAL IS
	PORT(A,B:IN STD_LOGIC_VECTOR(15 DOWNTO 0);
	ENABLE:IN STD_LOGIC;
	C:OUT STD_LOGIC);  -- IESIREA VA AVEA VALOAREA 1 DACA A=B SI 0 IN CAZ CONTRAR
END COMP_EGAL;

ARCHITECTURE ARCH_COMP_EGAL OF COMP_EGAL IS
BEGIN		 
	PROCESS
	VARIABLE INTER:STD_LOGIC;
	BEGIN 
		IF (ENABLE='1') THEN 
			INTER:='1';	
			FOR I IN 0 TO 15 LOOP
				IF A(I)/=B(I) THEN INTER:='0'; 
				END IF;	
			END LOOP;
			C<=INTER;
		ELSE C<='1';
		END IF;	
	WAIT ON A,B,ENABLE;
	END PROCESS;
END ARCH_COMP_EGAL;