LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

ENTITY DEMUX_OP IS
	PORT(X,S:IN STD_LOGIC;
	Y:OUT STD_LOGIC_VECTOR(1 DOWNTO 0 ));
END DEMUX_OP;

ARCHITECTURE ARCH_DEMUX_OP OF DEMUX_OP IS
BEGIN
	Y<=('0', X ) WHEN S='0' ELSE
	   ( X ,'0') WHEN S='1' ELSE
	   ('U','U') ;
END ARCH_DEMUX_OP;	