LIBRARY IEEE;
USE STD_LOGIC_1164.ALL;
USE STD_LOGIC_UNSIGNED.ALL;
USE STD_LOGIC_ARITH.ALL;

ENTITY INVERSOR IS
	PORT (A:IN STD_LOGIC_VECTOR(15 DOWNTO 0);
	B:OUT STD_LOGIC_VECTOR(15 DOWNTO 0)); 
END INVERSOR;

ARCHITECTURE ARCH_INVERSOR OF INVERSOR IS
SIGNAL INTER:STD_LOGIC_VECTOR(15 DOWNTO 0);
BEGIN							 
	ETICHETA:FOR I IN 0 TO 15 GENERATE
		INTER(I)<=NOT A(I);
	END GENERATE;  
	B<=INTER;
END ARCH_INVERSOR;	
	
	