LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

ENTITY MUX_AFISOR IS
	PORT( A,B,C,D:IN STD_LOGIC_VECTOR(6 DOWNTO 0);
	SEL:IN STD_LOGIC_VECTOR(1 DOWNTO 0);
	AF:OUT STD_LOGIC_VECTOR(6 DOWNTO 0));
END MUX_AFISOR;

ARCHITECTURE ARCH_MUX_AFISOR OF MUX_AFISOR IS
BEGIN				
	WITH SEL SELECT
	AF<=A WHEN "00",
	    B WHEN "01",
		C WHEN "10",
		D WHEN "11",
		"XXXXXXX" WHEN OTHERS;
END ARCH_MUX_AFISOR;