-- 0-CITIRE ADRESA 
-- 1-CITIRE CIFRA 1+2 PIN
-- 2-CITIRE CIFRA 3+4 PIN
-- 3-CITIRE OPERATIE+CHITANTA
-- 4-CITIRE SUMA PRIMII 8 BITI
-- 5-CITIRE SUNA ULTIMII 8 BITI
-- NUMARATORUL VAriable FI PE 3 BITI

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;

ENTITY NUMARATOR_COMANDA IS
	PORT(R,LD,CLK:IN STD_LOGIC;
	A:IN STD_LOGIC_VECTOR(2 DOWNTO 0);
	Y:OUT STD_LOGIC_VECTOR(2 DOWNTO 0)); 
END NUMARATOR_COMANDA;

ARCHITECTURE ARCH_NUMARATOR_COMANDA OF NUMARATOR_COMANDA IS
BEGIN
	P1:PROCESS(CLK,LD,R,A)
	VARIABLE INTER: STD_LOGIC_VECTOR(2 DOWNTO 0):="UUU";
	BEGIN
		IF CLK='1' AND CLK'EVENT THEN
			IF R='1' THEN 		  
				INTER:="000";
		    ELSIF LD='1' THEN
				INTER:=A;
		    ELSE	
				IF INTER="UUU" THEN
					INTER:="000";
				ELSE	
				 	INTER:=INTER+1;
				END IF;	 
			END IF;
			Y<=INTER;
		END IF;	
	END PROCESS P1;
END ARCH_NUMARATOR_COMANDA;		