LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;

ENTITY NUMARATOR_BANCNOTE IS
	PORT(R,LD,CLK:IN STD_LOGIC;
	A:IN STD_LOGIC_VECTOR(9 DOWNTO 0);
	Y:OUT STD_LOGIC_VECTOR(9 DOWNTO 0);
	CIN:OUT STD_LOGIC);	   -- CAND NU MAI SUNT BACNITE CIN DEVINE 1
END NUMARATOR_BANCNOTE;

ARCHITECTURE ARCH_NUMARATOR_BANCNOTE OF NUMARATOR_BANCNOTE IS
BEGIN	 
	P1:PROCESS(CLK,R,LD,A) 
	VARIABLE INTER:STD_LOGIC_VECTOR(9 DOWNTO 0):="1000010101";--533
	BEGIN  
		IF R='1' THEN 
			INTER:="0000000000";
		ELSIF LD='1' THEN 
			INTER:=A;
		ELSIF CLK='1' AND CLK'EVENT THEN
			INTER:=INTER-1;	
		END IF;	
		Y<=INTER;	
		IF INTER="0000000000" THEN CIN<='1';	 
		END IF;	
	END PROCESS;
END ARCH_NUMARATOR_BANCNOTE;	
		