LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;

ENTITY NUMARATOR_PIN IS
	PORT(R,LD,CLK:IN STD_LOGIC;
	A:IN STD_LOGIC_VECTOR(1 DOWNTO 0);
	Y:OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
	COUT:OUT STD_LOGIC); --SE ACTIVEAZA ATUNCI CAND CARDUL TREBUIE RETINUT (PIN INTRODUS INCORECT DE 3 ORI)
END NUMARATOR_PIN;

ARCHITECTURE ARCH_NUMARATOR_PIN OF NUMARATOR_PIN IS
BEGIN
	P1:PROCESS(CLK,LD,R,A)
	VARIABLE INTER: STD_LOGIC_VECTOR(1 DOWNTO 0):="00";
	BEGIN
		IF R='1' THEN 		  
			INTER:="00";
		ELSIF LD='1' THEN
			INTER:=A;
		ELSIF CLK='1' AND CLK'EVENT THEN
			INTER:=INTER+1; 
		END IF;
		Y<=INTER;
		IF INTER="11" THEN 
			COUT<='1'; --CARD RETINUT
			INTER:="00";
		ELSE COUT<='0';	
		END IF;
		END PROCESS;
END ARCH_NUMARATOR_PIN;		