LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;

ENTITY NUMARATOR_AFISOR IS
	PORT(CLK:IN STD_LOGIC;
	DOUT:OUT STD_LOGIC_VECTOR(1 DOWNTO 0));
END NUMARATOR_AFISOR;

ARCHITECTURE ARCH_NUMARATOR_AFISOR OF NUMARATOR_AFISOR IS
	SIGNAL INTER:STD_LOGIC_VECTOR(1 DOWNTO 0):="00";
BEGIN					  
	PROCESS(CLK)
	BEGIN		
		IF (CLK='1') AND (CLK'EVENT) THEN
			INTER<=INTER+1;
		END IF;
		DOUT<=INTER;
	END PROCESS;	
END ARCH_NUMARATOR_AFISOR;