LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;

ENTITY REINITIALIZARE_SUMA_NUMARATOR IS
	PORT(ENABLE:IN STD_LOGIC;
	SUMA_DISP:IN STD_LOGIC_VECTOR(15 DOWNTO 0);
	SUMA_SCAZUTA:IN STD_LOGIC_VECTOR(15 DOWNTO 0);
	SUMA_RAMASA:OUT STD_LOGIC_VECTOR(9 DOWNTO 0));
END REINITIALIZARE_SUMA_NUMARATOR;

ARCHITECTURE ARCH_REINITIALIZARE_SUMA_NUMARATOR OF REINITIALIZARE_SUMA_NUMARATOR IS
BEGIN
	PROCESS(ENABLE)
	VARIABLE V1,V2,V3:INTEGER;
	BEGIN			
		IF (ENABLE='1') AND (ENABLE'EVENT) THEN
			V1:=CONV_INTEGER(SUMA_DISP)-CONV_INTEGER(SUMA_SCAZUTA);
			V1:=V1/10;
			SUMA_RAMASA<=CONV_STD_LOGIC_VECTOR(V1,10);
		END IF;
	END PROCESS;	
END ARCH_REINITIALIZARE_SUMA_NUMARATOR;
	