LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;

ENTITY SCAZATOR IS
	PORT(A,B:IN STD_LOGIC_VECTOR(15 DOWNTO 0);
	ENABLE:IN STD_LOGIC;
	DIFERENTA:OUT STD_LOGIC_VECTOR(15 DOWNTO 0));
END SCAZATOR;

ARCHITECTURE ARCH_SCAZATOR OF SCAZATOR IS 

COMPONENT SUMATOR_N
	GENERIC (N:NATURAL:=16);
	PORT(A,B:IN STD_LOGIC_VECTOR(N-1 DOWNTO 0);
	CIN:IN STD_LOGIC;
	SUM:OUT STD_LOGIC_VECTOR(N-1 DOWNTO 0);
	COUT:OUT STD_LOGIC);  
END COMPONENT;	

COMPONENT INVERSOR
	PORT (A:IN STD_LOGIC_VECTOR(15 DOWNTO 0);
	B:OUT STD_LOGIC_VECTOR(15 DOWNTO 0)); 
END COMPONENT;

SIGNAL DIF_INTER,INTER1:STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL C:STD_LOGIC;
	   		
BEGIN					
	COMPLEMENT: INVERSOR PORT MAP(B,INTER1);
	SCADERE: SUMATOR_N PORT MAP(A,INTER1,'1',DIF_INTER,C); 
    DIFERENTA<=DIF_INTER WHEN ENABLE='1' ELSE
	 		   A;		
END;	
	