LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;

ENTITY SLL_1 IS 			
	PORT(X:IN STD_LOGIC_VECTOR(9 DOWNTO 0);
	Z:OUT STD_LOGIC_VECTOR(15 DOWNTO 0));
END SLL_1;

ARCHITECTURE ARCH_SLL_1 OF SLL_1 IS
BEGIN
	PROCESS(X)
	VARIABLE INTER:STD_LOGIC_VECTOR(15 DOWNTO 0):="0000000000000000";
	BEGIN  
	   INTER(10 DOWNTO 1):=X; 
	   Z<=INTER;
	END PROCESS;		
END ARCH_SLL_1;	