LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;

ENTITY SLL_3 IS 			
	PORT(X:IN STD_LOGIC_VECTOR(9 DOWNTO 0);
	Z:OUT STD_LOGIC_VECTOR(15 DOWNTO 0));
END SLL_3;

ARCHITECTURE ARCH_SLL_3 OF SLL_3 IS
BEGIN
	PROCESS(X)
	VARIABLE INTER:STD_LOGIC_VECTOR(15 DOWNTO 0):="0000000000000000";
	BEGIN  
	   INTER(12 DOWNTO 3):=X; 
	   Z<=INTER;
	END PROCESS;		
END ARCH_SLL_3;	
	
		