LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;

ENTITY SUMATOR_N IS
	GENERIC (N:NATURAL:=16);
	PORT(A,B:IN STD_LOGIC_VECTOR(N-1 DOWNTO 0);
	CIN:IN STD_LOGIC;
	SUM:OUT STD_LOGIC_VECTOR(N-1 DOWNTO 0);
	COUT:OUT STD_LOGIC);
END SUMATOR_N;

ARCHITECTURE ARCH_SUMATOR_N OF SUMATOR_N IS
COMPONENT SUMATOR_1 
	PORT (A,B,CIN:IN STD_LOGIC;
	S,COUT:OUT STD_LOGIC); 
END COMPONENT;
SIGNAL INT:STD_LOGIC_VECTOR(N-2 DOWNTO 0);
BEGIN
	ET0: FOR I IN 0 TO N-1 GENERATE
		ET1: IF I=0 GENERATE
			ET2:SUMATOR_1 PORT MAP (A(I),B(I),CIN,SUM(I),INT(I));
		END GENERATE;
		ET3: IF(I>0) AND (I<N-1) GENERATE
			ET4:SUMATOR_1 PORT MAP (A(I),B(I),INT(I-1),SUM(I),INT(I));
		END GENERATE;
		ET5: IF I=N-1 GENERATE
			ET6:SUMATOR_1 PORT MAP (A(I),B(I),INT(I-1),SUM(I),COUT);
		END GENERATE;
	END GENERATE;
END ARCH_SUMATOR_N;	
	
	