LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;

ENTITY SUMATOR_1 IS --SUMATOR COMPLET PE 1 BIT FOLOSIT CA SI COMPONENT LA SUMATOR_N
	PORT (A,B,CIN:IN STD_LOGIC;
	S,COUT:OUT STD_LOGIC);
END SUMATOR_1;

ARCHITECTURE ARCH_SUMATOR_1 OF SUMATOR_1 IS
SIGNAL INTER:STD_LOGIC;
BEGIN
	INTER<=A XOR B;
	S<=INTER XOR CIN;
	COUT<=(A AND B) OR (INTER AND CIN);
END ARCH_SUMATOR_1;	   


