LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;	   

ENTITY COMANDA IS 
	PORT(COMUTATOARE:IN STD_LOGIC_VECTOR(7 DOWNTO 0);
	CLOCK:IN STD_LOGIC;							
	CLOCK_DIV:IN STD_LOGIC; --TREBUIE LEGAT LA T10 SAU B8 PT DIVIZOR DE FRECV
	AFISOR:OUT STD_LOGIC_VECTOR(6 DOWNTO 0);
	ANOD:OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
	ELIB_CHITANTA, ELIB_CARD, ELIB_MONEDE, CARD_RETINUT, PIN_INCORECT,SOLD_INDISPONIBIL,SUMA_INSUFICIENTA,SUMA_MARE:OUT STD_LOGIC);
END COMANDA;

ARCHITECTURE ARCH_COMANDA OF COMANDA IS

COMPONENT NUMARATOR_COMANDA
	PORT(R,LD,CLK:IN STD_LOGIC;
	A:IN STD_LOGIC_VECTOR(2 DOWNTO 0);
	Y:OUT STD_LOGIC_VECTOR(2 DOWNTO 0)); 
END COMPONENT;

COMPONENT DEMUX_COMANDA
	PORT(X:IN STD_LOGIC;
		 S:IN STD_LOGIC_VECTOR(2 DOWNTO 0); --SELECTIA ESTE PE 3 BIBI	
	     Y:OUT STD_LOGIC_VECTOR(7 DOWNTO 0 )); --AVEM 8 IESIRI (VOM FOLOSI PRIMELE 6)
END COMPONENT;

COMPONENT CITIRE_ADRESA
	PORT(A:IN STD_LOGIC_VECTOR(7 DOWNTO 0); --8 COMUTAROARE
	CLK:IN STD_LOGIC;
	ADR:OUT STD_LOGIC_VECTOR(4 DOWNTO 0)); --ADRESA VA AVEA 5 BITI (ULTIMII 5 BITI DE PE COMUTATOARE)
END COMPONENT;

COMPONENT CITIRE_PIN 
	PORT (A:IN STD_LOGIC_VECTOR(7 DOWNTO 0);
	CLK,ENABLE:IN STD_LOGIC;
	PIN:OUT STD_LOGIC_VECTOR(15 DOWNTO 0));
END COMPONENT;

COMPONENT CITIRE_SUMA 
	PORT (A:IN STD_LOGIC_VECTOR(7 DOWNTO 0);
	CLK,ENABLE:IN STD_LOGIC;
	SUMA:OUT STD_LOGIC_VECTOR(15 DOWNTO 0));
END COMPONENT;

COMPONENT CITIRE_OP_CHITANTA
	PORT(A:IN STD_LOGIC_VECTOR(7 DOWNTO 0); --8 COMUTAROARE
	CLK,ENABLE:IN STD_LOGIC;
	OPERATIE,CHITANTA:OUT STD_LOGIC); --OPERATIA ESTE PRIMA 
END COMPONENT;	  

COMPONENT COMP_EGAL
	PORT(A,B:IN STD_LOGIC_VECTOR(15 DOWNTO 0);
	ENABLE:IN STD_LOGIC;
	C:OUT STD_LOGIC);  -- IESIREA VA AVEA VALOAREA 1 DACA A=B SI 0 IN CAZ CONTRAR
END COMPONENT;	

COMPONENT ROM_PIN
	PORT (ADR_PIN: IN STD_LOGIC_VECTOR(4 DOWNTO 0); -- VOM AVEA 32 DE PINURI, DECI 5 BITI PT ADRESE
	PIN_MEMORIE:OUT STD_LOGIC_VECTOR(15 DOWNTO 0)); --PINUL ARE 4 CIFRE=> 16 BITI PT PIN 
END COMPONENT;

COMPONENT NUMARATOR_PIN
	PORT(R,LD,CLK:IN STD_LOGIC;
	A:IN STD_LOGIC_VECTOR(1 DOWNTO 0);
	Y:OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
	COUT:OUT STD_LOGIC); --SE ACTIVEAZA ATUNCI CAND CARDUL TREBUIE RETINUT (PIN INTRODUS INCORECT DE 3 ORI)
END COMPONENT;

COMPONENT DEMUX_OP
	PORT(X,S:IN STD_LOGIC;
	Y:OUT STD_LOGIC_VECTOR(1 DOWNTO 0 ));
END COMPONENT;	 

COMPONENT COMP_MAI_MIC_SAU_EGAL
	PORT (A,B:IN STD_LOGIC_VECTOR(15 DOWNTO 0);	 
		  ENABLE:IN STD_LOGIC;	
		  C:OUT STD_LOGIC); --IESIREA VA AVEA VALOAREA 1 DACA B<=A SI 0 IN CAZ CONTRAR
END COMPONENT;	  

COMPONENT NUMARATOR_BANCNOTE
	PORT(R,LD,CLK:IN STD_LOGIC;
	A:IN STD_LOGIC_VECTOR(9 DOWNTO 0);
	Y:OUT STD_LOGIC_VECTOR(9 DOWNTO 0);
	CIN:OUT STD_LOGIC);	   -- CAND NU MAI SUNT BACNITE CIN DEVINE 1
END COMPONENT;	

COMPONENT SUMA_DISP
	PORT(A:IN STD_LOGIC_VECTOR(9 DOWNTO 0);
	Y:OUT STD_LOGIC_VECTOR(15 DOWNTO 0));
END COMPONENT;	

COMPONENT RAM_SOLD
	PORT (ADR_CARD: IN STD_LOGIC_VECTOR(4 DOWNTO 0);
	SOLD_UTILIZATOR:OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
	DIN:IN STD_LOGIC_VECTOR(15 DOWNTO 0);
	WE: IN STD_LOGIC); 
END COMPONENT;

COMPONENT REINITIALIZARE_SUMA_NUMARATOR
	PORT(ENABLE:IN STD_LOGIC;
	SUMA_DISP:IN STD_LOGIC_VECTOR(15 DOWNTO 0);
	SUMA_SCAZUTA:IN STD_LOGIC_VECTOR(15 DOWNTO 0);
	SUMA_RAMASA:OUT STD_LOGIC_VECTOR(9 DOWNTO 0));
END COMPONENT;	  

COMPONENT SCAZATOR 
	PORT(A,B:IN STD_LOGIC_VECTOR(15 DOWNTO 0); 
	ENABLE:IN STD_LOGIC;
	DIFERENTA:OUT STD_LOGIC_VECTOR(15 DOWNTO 0));
END COMPONENT;

COMPONENT DIVIZOR
	PORT(ENABLE:IN STD_LOGIC;
	CLOCK_DIV:IN STD_LOGIC;
	CLK:OUT STD_LOGIC);
END COMPONENT;	  

COMPONENT NUMARATOR_AFISOR
	PORT(CLK:IN STD_LOGIC;
	DOUT:OUT STD_LOGIC_VECTOR(1 DOWNTO 0));
END COMPONENT;		 

COMPONENT MUX_AFISOR
	PORT( A,B,C,D:IN STD_LOGIC_VECTOR(6 DOWNTO 0);
	SEL:IN STD_LOGIC_VECTOR(1 DOWNTO 0);
	AF:OUT STD_LOGIC_VECTOR(6 DOWNTO 0));
END COMPONENT;	

COMPONENT ROM_AFISOR
	PORT (ADR_CHAR: IN STD_LOGIC_VECTOR(3 DOWNTO 0); -- VOM AFISA IN HEXA, AVEM NEVOIE DE 4 BITI PT REPREZENTAREA IN BINAR
	ENABLE:IN STD_LOGIC;
	CHAR:OUT STD_LOGIC_VECTOR(6 DOWNTO 0)); --AVEM 7 SEGMENTE
END COMPONENT;

SIGNAL SEL_DEMUX: STD_LOGIC_VECTOR(2 DOWNTO 0); --IESIRE NUMARATOR_COMANDA, SELECTIE DEMUX_COMANDA
SIGNAL ADRESA_CARD:STD_LOGIC_VECTOR(4 DOWNTO 0);
SIGNAL EN:STD_LOGIC_VECTOR(7 DOWNTO 0):="00000000"; --IESIREA DEMULTIBLEXORULUI (O FOLOSIM PT CITIRI)
SIGNAL PIN_INTRODUS,PIN_MEMORIE,SUMA_INTRODUSA,SUMA_DISPONIBILA: STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL CLK1,CLK2,CLK3,RESET_COMANDA,COUT_PIN:STD_LOGIC:='0';   --CLK1 IL FOLOSIM CA SI CLOCK PT CITIRE_PIN, IAR CLK2 PT CITIRE_SUMA, CLK3 PT COMP CU 1000
SIGNAL OPERATIE, CHITANTA,P_INCORECT,WE,CIN_NUMARATOR:STD_LOGIC;-- P_INCORECT=PIN_INCORECT'DRIVING VALUE 
SIGNAL ENABLE1,ENABLE2,ENABLE3,ENABLE4:STD_LOGIC:='1';--ENABLE1 - IESIRE COMP_EGAL, ENABLE2-IESIRE COMP CU 1000,ENABLE3-IESIRE COMP CU SOLD, ENABLE 4-COMP CU SUMA DISPOIBILA
SIGNAL Y,SEL_AFISOR:STD_LOGIC_VECTOR(1 DOWNTO 0);--Y IESIRE NUMARATOR PIN 		
SIGNAL OP:STD_LOGIC_VECTOR(1 DOWNTO 0); --OP(O) DEVINE IESIREA DEMUX DACA OPERATIA ALEASA DE UTILIZATOR ESTE 0, ALTFEL IESIREA DEMUX VA FI OP(1)
SIGNAL SOLD,SOLD_NOU:STD_LOGIC_VECTOR(15 DOWNTO 0); 			
SIGNAL SUMA_NOUA, SUMA_NUMARATOR:STD_LOGIC_VECTOR(9 DOWNTO 0);	   
SIGNAL AF1, AF2,AF3,AF4: STD_LOGIC_VECTOR(6 DOWNTO 0);	   --AF4 PRIMUL CARACTER
SIGNAL CLOCK_AFISOR:STD_LOGIC;

														 
BEGIN
   C1:  NUMARATOR_COMANDA PORT MAP (RESET_COMANDA,P_INCORECT,CLOCK,"001",SEL_DEMUX);
   C2:  DEMUX_COMANDA PORT MAP('1',SEL_DEMUX,EN); --PE INTRAREA DEMUX PUNEM MEREU 1
   C3:  CITIRE_ADRESA PORT MAP(COMUTATOARE,EN(0),ADRESA_CARD);
   C4:  CITIRE_PIN PORT MAP(COMUTATOARE,CLK1,EN(0),PIN_INTRODUS);
   C5:  CITIRE_OP_CHITANTA PORT MAP(COMUTATOARE,EN(3),EN(0),OPERATIE,CHITANTA);
   C6:  CITIRE_SUMA PORT MAP(COMUTATOARE,CLK2,EN(0),SUMA_INTRODUSA);
   C7:  ROM_PIN PORT MAP(ADRESA_CARD,PIN_MEMORIE); --CITESTE PINUL DIN MEMORIE
   C8:  COMP_EGAL PORT MAP(PIN_INTRODUS,PIN_MEMORIE,EN(2),ENABLE1); 
   C9:  NUMARATOR_PIN PORT MAP(EN(0),'0',P_INCORECT,"00",Y,COUT_PIN);	 
   C10: DEMUX_OP PORT MAP(ENABLE1,OPERATIE,OP);
   C11: COMP_MAI_MIC_SAU_EGAL PORT MAP("0000001111101000",SUMA_INTRODUSA,CLK3,ENABLE2);	 --COMPARA CU 1000 EURO
   C12: COMP_MAI_MIC_SAU_EGAL PORT MAP(SOLD,SUMA_INTRODUSA,ENABLE2,ENABLE3);				 --COMPARA CU SOLDUL
   C13: NUMARATOR_BANCNOTE PORT MAP('0',WE,'0',SUMA_NOUA, SUMA_NUMARATOR,CIN_NUMARATOR);
   C14: SUMA_DISP PORT MAP(SUMA_NUMARATOR,SUMA_DISPONIBILA);								
   C15: COMP_MAI_MIC_SAU_EGAL PORT MAP(SUMA_DISPONIBILA,SUMA_INTRODUSA,ENABLE3,ENABLE4);	 --COMPARA CU SUMA DISPONIBILA
   C16: RAM_SOLD PORT MAP(ADRESA_CARD,SOLD,SOLD_NOU,WE);	   
   C17: REINITIALIZARE_SUMA_NUMARATOR PORT MAP(WE,SUMA_DISPONIBILA,SUMA_INTRODUSA,SUMA_NOUA); 
   C18: SCAZATOR PORT MAP(SOLD,SUMA_INTRODUSA,CLK3,SOLD_NOU);
   
   WE<='0' WHEN EN(0)='1' ELSE
	   ENABLE2 AND ENABLE3 AND ENABLE4 AND NOT(OP(0));
	   
   CLK1<=(EN(1) OR EN(2)) AND CLOCK;
   CLK2<=(EN(4) OR EN(5)) AND CLOCK;
   P_INCORECT<=NOT ENABLE1;																	   
   
   --LEDURI				 
   CARD_RETINUT<=COUT_PIN;
   PIN_INCORECT<= NOT ENABLE1; --CAND ENABLE1=0 SE APRINDE LED PT PIN_INCORECT
   SUMA_MARE<=OP(1) AND EN(5) AND(NOT ENABLE2);
   SOLD_INDISPONIBIL<=ENABLE2 AND (NOT ENABLE3);
   SUMA_INSUFICIENTA<=ENABLE3 AND (NOT ENABLE4);		    
   ELIB_MONEDE<=WE;
   ELIB_CHITANTA<=(OP(0) OR WE) AND CHITANTA;
   ELIB_CARD<=( OP(1) AND (NOT ENABLE2) ) OR ( ENABLE2 AND (NOT ENABLE3) ) OR ( ENABLE3 AND (NOT ENABLE4) ) OR WE OR OP(0);


   RESET_COMANDA<=(COUT_PIN OR WE OR OP(0) OR EN(5)) AND NOT EN(0);

	P3:PROCESS(SUMA_INTRODUSA,EN(5),OP(1))
	BEGIN
    	IF SUMA_INTRODUSA(15)/='U' AND (EN(5)='1' AND OP(1)='1') THEN
			CLK3<='1';
		ELSE CLK3<='U';	
	END IF;
	END PROCESS;			
	
	--AFISARE SOLD
	C19:ROM_AFISOR PORT MAP(SOLD(15 DOWNTO 12),OP(0),AF4);
	C20:ROM_AFISOR PORT MAP(SOLD(11 DOWNTO 8),OP(0),AF3);
	C21:ROM_AFISOR PORT MAP(SOLD(7 DOWNTO 4),OP(0),AF2);
	C22:ROM_AFISOR PORT MAP(SOLD(3 DOWNTO 0),OP(0),AF1);
	C23:DIVIZOR PORT MAP(OP(0),CLOCK_DIV,CLOCK_AFISOR);
	C24:NUMARATOR_AFISOR PORT MAP(CLOCK_AFISOR,SEL_AFISOR);	 
	C25:MUX_AFISOR PORT MAP(AF1,AF2,AF3,AF4,SEL_AFISOR,AFISOR);	
	
	--ANODURI
	ANOD(0)<=SEL_AFISOR(0) OR SEL_AFISOR(1);
	ANOD(1)<=NOT (SEL_AFISOR(0)) OR SEL_AFISOR(1);
	ANOD(2)<=NOT (SEL_AFISOR(1)) OR SEL_AFISOR(0);
	ANOD(3)<=NOT(SEL_AFISOR(0)) OR NOT (SEL_AFISOR(1));
	
END ARCH_COMANDA;