acom -dbg "$DSN/src/hex2led.vhd"
acom -dbg "$DSN/src/control.asf"
acom -dbg "$DSN/src/and2.vhd"
acom -dbg "$DSN/src/cnt_4b.vhd"
acom -dbg "$DSN/src/cnt_bcd.bde"
acom -netlist -skip e -dbg "$DSN/src/cnt_bcd2.bde"
acom -dbg "$DSN/src/freq_top.bde"
acom -dbg "$DSN/src/testbench_cnt_bcd_conf.vhd"
acom -dbg "$DSN/src/testbench/testbenchpack.vhd"
acom -dbg "$DSN/src/testbench/testbench.vhd"
