# Project: Project3
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = p35main.o p35a.o p35b.o $(RES)
LINKOBJ  = p35main.o p35a.o p35b.o $(RES)
LIBS =  -L"D:/Utilitare/Dev-Cpp/lib"  
INCS =  -I"D:/Utilitare/Dev-Cpp/include" 
CXXINCS =  -I"D:/Utilitare/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"D:/Utilitare/Dev-Cpp/include/c++/3.4.2/backward"  -I"D:/Utilitare/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"D:/Utilitare/Dev-Cpp/include/c++/3.4.2"  -I"D:/Utilitare/Dev-Cpp/include" 
BIN  = Project3.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before Project3.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "Project3.exe" $(LIBS)

p35main.o: p35main.cpp
	$(CPP) -c p35main.cpp -o p35main.o $(CXXFLAGS)

p35a.o: p35a.cpp
	$(CPP) -c p35a.cpp -o p35a.o $(CXXFLAGS)

p35b.o: p35b.cpp
	$(CPP) -c p35b.cpp -o p35b.o $(CXXFLAGS)
