# Project: clock
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe -D__DEBUG__
CC   = gcc.exe -g -Wall -D__DEBUG__
WINDRES = windres.exe
RES  = 
OBJ  = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS =  -L"lib" C:/Dev-Cpp/lib/conio.o  -lgmon -pg  -g3 
INCS =  -I"include" 
CXXINCS =  -I"lib/gcc/mingw32/3.4.2/include"  -I"include/c++/3.4.2/backward"  -I"include/c++/3.4.2/mingw32"  -I"include/c++/3.4.2"  -I"include" 
BIN  = clock.exe
CXXFLAGS = $(CXXINCS)   -g -Wall -pg -g3
CFLAGS = $(INCS)   -g -Wall -pg -g3
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before clock.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o "clock.exe" $(LIBS)

main.o: main.c 
	$(CC) -c main.c -o main.o $(CFLAGS)
