TITLE CITIRE SI CALCULARE
;ENTER=0DH
;SPACE=20H

DATA2 SEGMENT PARA PUBLIC 'DATA'
	NUMBER_OF_ELEMENTS		DW			0H
	ZECE					DW			0AH
	ENTER_					DB			0DH
	SPACE 					DB			20H
	INTERMEDIARY			DW			0H
DATA2 ENDS

COD2 SEGMENT PARA 'CODE'
PUBLIC CALCULARE
		ASSUME CS:COD2, DS:DATA2
		
CALCULARE PROC NEAR

		MOV CX, 0	;where we store the current number
		MOV BX, 0	;where we store the sum
		MOV DX, 0	;intermediary
		
	CITIRE:
		MOV AH, 01H
		INT 21H
		CMP AL, SPACE
		JE NEXT_NUMBER
		CMP AL, ENTER_
		JE TERMINARE
		
		SUB AL, 30H
		MOV BYTE PTR INTERMEDIARY, AL
		MOV AX, CX
		MUL ZECE
		ADD AX, INTERMEDIARY
		MOV CX, AX
		
	NEXT_NUMBER:
		ADD BX, CX
		INC NUMBER_OF_ELEMENTS
		JMP CITIRE
		
	TERMINARE:
		MOV AX, BX
		MOV DX, 0
		DIV NUMBER_OF_ELEMENTS
		RET
		
		CALCULARE ENDP
		COD2 ENDS
		END
		
		
		