EXTRN PRINTB:FAR

MDATA SEGMENT PARA PUBLIC 'DATA'
	SIR1 DB 12,15,47,21,58
	LGSIR1 DW $-SIR1
	SIR2 DB 56,41,23,58,41,23
	LGSI2R DW $-SIR2
	MIN1 DB 200
	MIN2 DB 200
	MAX1 DB 0
	MAX2 DB 0
	MESSAGE1 DB 0DH,0AH,'THE SMALLES NUMBER FROM FIRST ARRAY: $'
MDATA ENDS

MSTACK SEGMENT PARA PUBLIC 'STACK'
	DB 64 DUP('MY STACK')
MSTACK ENDS

MCODE SEGMENT PARA PUBLIC 'CODE'
	START PROC FAR
	ASSUME CS:MCODE,DS:MDATA,SS:MSTACK
	PUSH DS
	XOR AX,AX
	PUSH AX
	MOV AX,MDATA
	MOV DS,AX

	MOV SI,0

	FINDMIN1:
		MOV AH,0
		MOV AL,SIR1[SI]
		CMP AL,MIN1
		JB ISLOWER
		INC SI
		JMP END_M1
		ISLOWER:
		MOV MIN1,AL
		INC SI
		END_M1:
		CMP SI,LGSIR1
		JNE FINDMIN1
	
	MOV DX,OFFSET MESSAGE1
	MOV AH,09H
	INT 21H
	MOV AH,0
	MOV AL,MIN1
	CALL PRINTB

	MOV AH,4CH
	INT 21H
	RET
START ENDP
MCODE ENDS
END START