DATA SEGMENT PARA PUBLIC 'DATA'
STRING DB "iulia"
LEN DB $-STRING
DATA ENDS
CODE SEGMENT PARA PUBLIC 'CODE'
ASSUME CS:CODE, DS:DATA
START PROC FAR
ASSUME CS:CODE, DS:DATA
PUSH DS ;prepare to return to DOS
XOR AX,AX
PUSH AX
MOV AX,DATA; initialise DS
MOV DS, AX

XOR SI, SI ;intialize SI with 0
MOV CX, WORD PTR LEN
L: SUB STRING[SI], 32 ;turn every small letter into a CAP one by subtracting 32
INC SI
LOOP L
RET
START ENDP

CODE ENDS

END START