DATA SEGMENT PARA PUBLIC 'DATA'
NUMBERS DB 10 DUP(?)
DATA ENDS
CODE SEGMENT PARA PUBLIC 'CODE'
START PROC FAR
ASSUME CS:CODE, DS:DATA
PUSH DS ;prepare to return to DOS
XOR AX,AX
PUSH AX
MOV AX,DATA; initialise DS
MOV DS, AX

MOV AX, 505 ; putting a value in the AX register
MOV CX, 10
MOV SI,0
L1:
CWD ;convert word to dword in AX
DIV CX ;AX stores the quotient and DX stores the rest
MOV NUMBERS[SI], DL
ADD NUMBERS[SI], '0'
INC SI
CMP AX, 0
JNE L1

MOV CX, SI
MOV AH, 02H ;02H is used to WRITE CHARACTER TO STANDARD OUTPUT
DEC SI

L2: MOV DL, NUMBERS[SI]
INT 21H
DEC SI
LOOP L2

 
RET
START ENDP

CODE ENDS

END START