print macro msg  
   mov ah,09h  
   mov dx,offset msg  
   int 21h  
 endm 
 
DATA SEGMENT PARA PUBLIC 'DATA'
NUMBERS DB 1,2,3,4
LEN DB $-NUMBERS
MESSAGE DB 'The average is:'
LENMSG DW $-MESSAGE
DATA ENDS
CODE SEGMENT PARA PUBLIC 'CODE'
START PROC FAR
ASSUME CS:CODE, DS:DATA
PUSH DS ;prepare to return to DOS
XOR AX,AX
PUSH AX
MOV AX,DATA; initialise DS
MOV DS, AX

XOR AX, AX
XOR CX, CX
MOV CL, LEN
XOR SI, SI

L: ADD AL, NUMBERS[SI]
INC SI
LOOP L

DIV LEN
XOR AH, AH
MOV BL, 10
DIV BL

MOV SI, LENMSG
MOV MESSAGE[SI], AL
ADD MESSAGE[SI], '0'
MOV MESSAGE[SI+1], AH
ADD MESSAGE[SI+1], '0'
MOV MESSAGE[SI+2], '$'

LEA DX, MESSAGE
MOV AH, 09H
INT 21H
RET
START ENDP

CODE ENDS

END START