DATA SEGMENT PARA PUBLIC 'DATA'
MEM32A DD 316423
MEM32B DD 156739
DATA ENDS

CODE SEGMENT PARA PUBLIC 'CODE'
START PROC FAR 
ASSUME CS:CODE, DS:DATA
PUSH DS
XOR AX,AX
PUSH AX
MOV AX, DATA
MOV DS, AX

;MY PROGRAM'S INSTRUCTIONS

MOV AX, WORD PTR MEM32A[0] ;load inf. word
MOV DX, WORD PTR MEM32A[2] ; load sup. word
SUB AX, WORD PTR MEM32B[0] ;subtract inf. word
SBB DX, WORD PTR MEM32B[2] ; subtract sup. word

	MOV AH, 004CH ;TERMINATE PROGRAM
	INT 21H
				
RET
START ENDP
CODE ENDS
END START
