alog -dbg "$DSN/src/and2.v"
alog -dbg "$DSN/src/and3.v"
alog -dbg "$DSN/src/and4.v"
acom -dbg "$DSN/src/cb4ce.vhd"
alog -dbg "$DSN/src/oscil.v"
acom -dbg "$DSN/src/c2or.vhd"
edfcomp "$DSN/src/crv.edn"
acom -dbg "$DSN/src/pfdiv.vhd"
acom -dbg "$DSN/src/filter.bde"
acom -dbg "$DSN/src/testbench/filter1_functional_tb.vhd"
