// FISIERUL: tabcuv.h

typedef struct{
       char *nume;
       int val;
       }cuvint;
cuvint       tabcuv[]={
      "int",1,          "char",2,         "float",3,        
      "double",4,       "struct",5,       "long",6,   
      "unsigned",7,    "union",8,         "short",9,  
      "auto",10,        "extern",11,      "static",12,
      "register",13,    "goto",14,        "return",15,
      "if",16,          "while",17,       "else",18,
      "switch",19,      "case",20,        "break",21,
      "continue",22,    "do",23,          "default",24,
      "for",25,         "sizeof",26,      "typedef",27,
      "",0,       };    
