		  LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;

ENTITY COMP_MAI_MIC_SAU_EGAL IS
	PORT (R:IN STD_LOGIC;
	 	  A,B:IN STD_LOGIC_VECTOR(15 DOWNTO 0);	 
		  ENABLE:IN STD_LOGIC;	
		  C:OUT STD_LOGIC); --IESIREA VA AVEA VALOAREA 1 DACA B<=A SI 0 IN CAZ CONTRAR
END COMP_MAI_MIC_SAU_EGAL;

ARCHITECTURE ARCH_COMP_MAI_MIC_SAU_EGAL OF COMP_MAI_MIC_SAU_EGAL IS
BEGIN
	PROCESS(ENABLE,A,B)
	VARIABLE X,Y:INTEGER;
	BEGIN
		IF R='1' THEN
			C<='0';
		ELSIF (ENABLE='1') THEN 
			X:=CONV_INTEGER(A);
			Y:=CONV_INTEGER(B);
			IF(Y<=X) THEN C<='1';
			ELSE C<='0';
			END IF;	
		END IF;
		
	END PROCESS;
	
END ARCH_COMP_MAI_MIC_SAU_EGAL;	
			
		