LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;   

ENTITY COMPARATOR_CARD_PIN IS
	PORT(ADRESA_PIN,PIN_INTRODUS:IN STD_LOGIC_VECTOR(15 DOWNTO 0);
	ENABLE:IN STD_LOGIC;
	iesire:OUT STD_LOGIC);  -- IESIREA VA AVEA VALOAREA 1 DACA A=B SI 0 IN CAZ CONTRAR
END COMPARATOR_CARD_PIN;

ARCHITECTURE ARCH_COMP_EGAL OF COMPARATOR_CARD_PIN IS
BEGIN		 
	PROCESS(ADRESA_PIN,PIN_INTRODUS,ENABLE)
	VARIABLE INTER:STD_LOGIC;
	BEGIN 
		IF (ENABLE='1') THEN 
			INTER:='1';	
			FOR I IN 0 TO 15 LOOP
				IF ADRESA_PIN(I)/=PIN_INTRODUS(I) THEN INTER:='L'; 
				END IF;	
			END LOOP;
			iesire<=INTER;
	
		END IF;	
	END PROCESS;
END ARCH_COMP_EGAL;