LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;

ENTITY DIVIZOR IS
	PORT(ENABLE:IN STD_LOGIC; 
	CLOCK_DIV:IN STD_LOGIC; 
	CLK:OUT STD_LOGIC);
END DIVIZOR;

ARCHITECTURE ARCH_DIVIZOR OF DIVIZOR IS
SIGNAL INTER: STD_LOGIC_VECTOR(16 DOWNTO 0):="00000000000000000";
SIGNAL C:STD_LOGIC:='1';
BEGIN
	PROCESS(CLOCK_DIV,ENABLE,INTER,C)
	BEGIN				 
		IF ENABLE='1' THEN
			IF CLOCK_DIV='1' THEN
				INTER<=INTER+1;
				IF (INTER(16)='1') THEN 
					INTER(16)<='0';
					C<=NOT C;
					CLK<=C;
				END IF;	
			END IF;
		END IF;	
	END PROCESS;
END ARCH_DIVIZOR;	