LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

ENTITY CITIRE_SUMA IS
	PORT (A:IN STD_LOGIC_VECTOR(7 DOWNTO 0);
	CLK:IN STD_LOGIC;
	SUMA:OUT STD_LOGIC_VECTOR(15 DOWNTO 0));
END CITIRE_SUMA;

ARCHITECTURE ARCH_CITIRE_SUMA OF CITIRE_SUMA IS

COMPONENT REGISTRU
	PORT(A:IN STD_LOGIC_VECTOR(7 DOWNTO 0);
	CLK:IN STD_LOGIC;
	Y:OUT STD_LOGIC_VECTOR(7 DOWNTO 0));
END COMPONENT;		

SIGNAL R1,R2,R0:STD_LOGIC_VECTOR(7 DOWNTO 0);
SIGNAL INTER:STD_LOGIC_VECTOR(15 DOWNTO 0);

BEGIN		  
	C1:REGISTRU PORT MAP(R0,CLK,R1);
	C2:REGISTRU PORT MAP(R1,CLK,R2);	
	INTER(15 DOWNTO 8)<=R2;
	INTER(7 DOWNTO 0)<=R1; 						   
END ARCH_CITIRE_SUMA;	