LIBRARY IEEE;
USE ieee.STD_LOGIC_1164.ALL;

ENTITY CITIRE_PIN IS
	PORT (A:IN STD_LOGIC_VECTOR(7 DOWNTO 0);
	CLK,ENABLE:IN STD_LOGIC;
	PIN:OUT STD_LOGIC_VECTOR(15 DOWNTO 0));
END CITIRE_PIN;

ARCHITECTURE ARCH_CITIRE_PIN OF CITIRE_PIN IS

COMPONENT REGISTRU
	PORT(A:IN STD_LOGIC_VECTOR(7 DOWNTO 0);
	CLK,ENABLE:IN STD_LOGIC;
	Y:OUT STD_LOGIC_VECTOR(7 DOWNTO 0));
END COMPONENT;		

SIGNAL R1,R2:STD_LOGIC_VECTOR(7 DOWNTO 0);
SIGNAL INTER:STD_LOGIC_VECTOR(15 DOWNTO 0);

BEGIN
	C1:REGISTRU PORT MAP(A,CLK,ENABLE,R1);
	C2:REGISTRU PORT MAP(R1,CLK,ENABLE,R2);  
    INTER(15 DOWNTO 8)<=R2 WHEN ENABLE ='1' ELSE
						"--------";
	INTER(7 DOWNTO 0)<=R1 WHEN ENABLE ='1' ELSE
						"--------";
	PIN<="----------------" WHEN ENABLE='1' ELSE
	     INTER WHEN CLK='1';
END ARCH_CITIRE_PIN;	