LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

ENTITY REGISTRU IS
	PORT(A:IN STD_LOGIC_VECTOR(7 DOWNTO 0);
	CLK,ENABLE:IN STD_LOGIC;
	Y:OUT STD_LOGIC_VECTOR(7 DOWNTO 0));
END REGISTRU;

ARCHITECTURE ARCH_REGISTRU OF REGISTRU IS
BEGIN
	PROCESS(CLK,ENABLE) 
	VARIABLE INTER:STD_LOGIC_VECTOR(7 DOWNTO 0);
	BEGIN
		IF (CLK='1') AND (CLK'EVENT) THEN
			INTER:=A;
		END IF;	   
		IF (ENABLE='1') THEN
			Y<="UUUUUUUU";
			INTER:="UUUUUUUU";
		ELSE 	  
			Y<=INTER;
		END IF;	
	END PROCESS;
END ARCH_REGISTRU;	