acom -dbg "$DSN/src/gates.vhd"
acom -dbg "$DSN/src/fub1.bde"
acom -dbg "$DSN/src/fub2.bde"
acom -dbg "$DSN/src/fub3.bde"
acom -dbg "$DSN/src/fub4.bde"
acom -dbg "$DSN/src/fub5.bde"
acom -dbg "$DSN/src/fub0.bde"
acom -dbg "$DSN/src/sn7485_top.bde"
acom -dbg "$DSN/src/sn7485_top_tb.vhd"
comp "$DSN/src/external/foreign1.dlm"
