--------------------------------------------------------------------
-- Name: processor_top.vhd
-- Created: 30/9/2003 @ 12:54
-- Description: this file contains the top level entity
-- Generated by: Handel-C Hardware Compiler, version 3.2.2710
-- Family: XilinxVirtex
-- Output Style: Generic
--
-- File structure:
--
-- ¬processor_top.vhd
--   +processor_hcc.vhd
--------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_arith.all;
library HandelC;
use HandelC.HandelCpackage.all;
-- this is the top level entity
entity processor_top is
  -- interface description
  port (
    clk : in std_logic;
    data_read : out std_logic;
    inp : in std_logic_vector(7 downto 0);
    outp : out std_logic_vector(7 downto 0);
    rst : in std_logic
  );
end;

-- this is the top level entity
architecture behaviour of processor_top is
  -- Component declaration
  component processor_hcc
  port (
    globals_CForkIn_out : out unsigned(0 downto 0);
    globals_GND : in unsigned(0 downto 0);
    globals_PWR : in unsigned(0 downto 0);
    globals_TrueZ_1_out : out unsigned(0 downto 0);
    globals_TrueZ_out : out unsigned(0 downto 0);
    globals_clk_1 : in std_logic;
    globals_clk_out : out std_logic;
    globals_inp : in std_logic_vector(7 downto 0);
    globals_rst : in std_logic;
    globals_value_Out_out : out unsigned(7 downto 0);
    globals_value_read_Out_out : out unsigned(0 downto 0)
  );
  end component;
  for all : processor_hcc use entity work.processor_hcc;

  -- Power cable
  constant globals_PWR : unsigned(0 downto 0) := "1";
  -- Ground cable
  constant globals_GND : unsigned(0 downto 0) := "0";
  -- global connection
  signal globals_clk : std_logic;
  -- global connection
  signal globals_TrueZ : unsigned(0 downto 0);
  -- global connection
  signal globals_TrueZ_1 : unsigned(0 downto 0);
  -- global connection
  signal globals_CForkIn : unsigned(0 downto 0);
  -- global connection
  signal globals_value_read_Out : unsigned(0 downto 0);
  -- global connection
  signal globals_value_Out : unsigned(7 downto 0);
  -- Port connection
  signal Instance0_globals_GND : unsigned(0 downto 0);
  -- Port connection
  signal Instance0_globals_PWR : unsigned(0 downto 0);

begin

  -- root group
    -- group netlist root
      -- global connection
      outp <= to_std_logic(globals_value_Out);
      -- global connection
      data_read <= to_std_logic(globals_value_read_Out);
    -- end of group netlist root

    -- Instantiation
    Instance0_globals_GND <= globals_GND;
    Instance0_globals_PWR <= globals_PWR;
    Instance0 : processor_hcc
      port map (globals_CForkIn_out => globals_CForkIn,
                globals_GND => Instance0_globals_GND,
                globals_PWR => Instance0_globals_PWR,
                globals_TrueZ_1_out => globals_TrueZ_1,
                globals_TrueZ_out => globals_TrueZ,
                globals_clk_1 => clk,
                globals_clk_out => globals_clk,
                globals_inp => inp,
                globals_rst => rst,
                globals_value_Out_out => globals_value_Out,
                globals_value_read_Out_out => globals_value_read_Out
    );
  -- end of root group


end;

