--------------------------------------------------------------------
-- Name: processor_hcc.vhd
-- Created: 30/9/2003 @ 12:54
-- Description: source file 'C:\My_Designs_61\Samples_61\PROCESSOR_DK\processor.hcc'
-- Generated by: Handel-C Hardware Compiler, version 3.2.2710
-- Family: XilinxVirtex
-- Output Style: Generic
--
-- File structure:
--
-- ¬processor_top.vhd
--   +processor_hcc.vhd
--------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_arith.all;
library HandelC;
use HandelC.HandelCpackage.all;
-- global logic, declared in 'C:\My_Designs_61\Samples_61\PROCESSOR_DK\processor.hcc'
entity processor_hcc is
  -- interface description
  port (
    globals_CForkIn_out : out unsigned(0 downto 0);
    globals_clk_1 : in std_logic;
    globals_clk_out : out std_logic;
    globals_GND : in unsigned(0 downto 0);
    globals_inp : in std_logic_vector(7 downto 0);
    globals_PWR : in unsigned(0 downto 0);
    globals_rst : in std_logic;
    globals_TrueZ_1_out : out unsigned(0 downto 0);
    globals_TrueZ_out : out unsigned(0 downto 0);
    globals_value_Out_out : out unsigned(7 downto 0);
    globals_value_read_Out_out : out unsigned(0 downto 0)
  );
end;

library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_arith.all;
library HandelC;
use HandelC.HandelCpackage.all;
-- handel-c function: 'main' from source file: 'C:\My_Designs_61\Samples_61\PROCESSOR_DK\processor.hcc'
entity processor_hcc_main is
  -- interface description
  port (
    Call0_RE : in unsigned(0 downto 0);
    globals_acc_Out_out : out unsigned(7 downto 0);
    globals_CForkIn_out : out unsigned(0 downto 0);
    globals_clk : in std_logic;
    globals_clk_out : out std_logic;
    globals_GND : in unsigned(0 downto 0);
    globals_pc_Out_out : out unsigned(4 downto 0);
    globals_PWR : in unsigned(0 downto 0);
    globals_Receive : in unsigned(0 downto 0);
    globals_rst : in std_logic;
    globals_StartOut_out : out unsigned(0 downto 0);
    globals_Transmit : in unsigned(0 downto 0);
    globals_TrueZ_1_out : out unsigned(0 downto 0);
    globals_TrueZ_out : out unsigned(0 downto 0);
    globals_value_Out_out : out unsigned(7 downto 0);
    globals_value_read_Out_out : out unsigned(0 downto 0);
    globals_W_0 : in unsigned(7 downto 0);
    globals_W_1 : in unsigned(7 downto 0);
    globals_W_2_out : out unsigned(0 downto 0);
    globals_W_3_out : out unsigned(0 downto 0);
    globals_W_4_out : out unsigned(0 downto 0);
    globals_W_5_out : out unsigned(0 downto 0);
    globals_W_6_out : out unsigned(0 downto 0);
    globals_W_7 : in unsigned(8 downto 0)
  );
end;

-- global logic, declared in 'C:\My_Designs_61\Samples_61\PROCESSOR_DK\processor.hcc'
architecture behaviour of processor_hcc is
  -- Component declaration of function
  component processor_hcc_main
  port (
    Call0_RE : in unsigned(0 downto 0);
    globals_CForkIn_out : out unsigned(0 downto 0);
    globals_GND : in unsigned(0 downto 0);
    globals_PWR : in unsigned(0 downto 0);
    globals_Receive : in unsigned(0 downto 0);
    globals_StartOut_out : out unsigned(0 downto 0);
    globals_Transmit : in unsigned(0 downto 0);
    globals_TrueZ_1_out : out unsigned(0 downto 0);
    globals_TrueZ_out : out unsigned(0 downto 0);
    globals_W_0 : in unsigned(7 downto 0);
    globals_W_1 : in unsigned(7 downto 0);
    globals_W_2_out : out unsigned(0 downto 0);
    globals_W_3_out : out unsigned(0 downto 0);
    globals_W_4_out : out unsigned(0 downto 0);
    globals_W_5_out : out unsigned(0 downto 0);
    globals_W_6_out : out unsigned(0 downto 0);
    globals_W_7 : in unsigned(8 downto 0);
    globals_acc_Out_out : out unsigned(7 downto 0);
    globals_clk : in std_logic;
    globals_clk_out : out std_logic;
    globals_pc_Out_out : out unsigned(4 downto 0);
    globals_rst : in std_logic;
    globals_value_Out_out : out unsigned(7 downto 0);
    globals_value_read_Out_out : out unsigned(0 downto 0)
  );
  end component;
  for all : processor_hcc_main use entity work.processor_hcc_main;

  -- Bitwise OR
  signal globals_Transmit : unsigned(0 downto 0);
  -- Multiplexer
  signal globals_W_0 : unsigned(7 downto 0);
  -- Bitwise OR
  signal globals_Receive : unsigned(0 downto 0);
  -- Multiplexer
  signal globals_W_1 : unsigned(7 downto 0);
  -- ROM 'program' read address
  signal ROM_program_RdAddr : unsigned(4 downto 0);
  -- ROM 'program' output
  signal globals_W_7 : unsigned(8 downto 0);
  -- global connection
  signal globals_clk : std_logic;
  -- global connection
  signal globals_W_2 : unsigned(0 downto 0);
  -- global connection
  signal globals_W_3 : unsigned(0 downto 0);
  -- global connection
  signal globals_W_4 : unsigned(0 downto 0);
  -- global connection
  signal globals_TrueZ : unsigned(0 downto 0);
  -- global connection
  signal globals_W_5 : unsigned(0 downto 0);
  -- global connection
  signal globals_TrueZ_1 : unsigned(0 downto 0);
  -- global connection
  signal globals_CForkIn : unsigned(0 downto 0);
  -- global connection
  signal globals_W_6 : unsigned(0 downto 0);
  -- global connection
  signal globals_acc_Out : unsigned(7 downto 0);
  -- global connection
  signal globals_pc_Out : unsigned(4 downto 0);
  -- global connection
  signal globals_value_read_Out : unsigned(0 downto 0);
  -- global connection
  signal globals_value_Out : unsigned(7 downto 0);
  -- global connection
  signal globals_StartOut : unsigned(0 downto 0);

begin

  -- root group
    -- group file 'C:\My_Designs_61\Samples_61\PROCESSOR_DK\processor.hcc' root
      -- ROM 'program' read address
      ROM_program_RdAddr <= globals_pc_Out;
      -- ROM 'program'
      process(ROM_program_RdAddr) begin
        case ROM_program_RdAddr is
          when "00000" => globals_W_7 <= "000110010";
          when "00001" => globals_W_7 <= "000000011";
          when "00010" => globals_W_7 <= "000001000";
          when "00011" => globals_W_7 <= "000010011";
          when "00100" => globals_W_7 <= "000001000";
          when "00101" => globals_W_7 <= "000100011";
          when "00110" => globals_W_7 <= "000011100";
          when "00111" => globals_W_7 <= "000010001";
          when "01000" => globals_W_7 <= "000001010";
          when "01001" => globals_W_7 <= "000001110";
          when "01010" => globals_W_7 <= "000001001";
          when "01011" => globals_W_7 <= "000001100";
          when "01100" => globals_W_7 <= "000001001";
          when "01101" => globals_W_7 <= "000000001";
          when "01110" => globals_W_7 <= "000001111";
          when "01111" => globals_W_7 <= "000010111";
          when "10000" => globals_W_7 <= "000000000";
          when others => globals_W_7 <= "000000000";
        end case;
      end process;
    -- end of group file 'C:\My_Designs_61\Samples_61\PROCESSOR_DK\processor.hcc' root

    -- group channel
      -- Multiplexer
      process(globals_W_5, globals_inp, globals_W_4) begin
        if (to_std_logic(globals_W_5)='1') then
          globals_W_0 <= to_unsigned(globals_inp);
        elsif (to_std_logic(globals_W_4)='1') then
          globals_W_0 <= to_unsigned(globals_inp);
        else
          globals_W_0 <= "00000000";
        end if;
      end process;
    -- end of group channel

    -- group cjoin
      -- Bitwise OR
      globals_Transmit <= LOR(globals_W_5, globals_W_4);
    -- end of group cjoin

    -- group channel
      -- Multiplexer
      process(globals_W_6, globals_acc_Out) begin
        if (to_std_logic(globals_W_6)='1') then
          globals_W_1 <= globals_acc_Out;
        else
          globals_W_1 <= "00000000";
        end if;
      end process;
    -- end of group channel

    -- group cjoin
      -- Bitwise OR
      globals_Receive <= LOR(globals_W_3, globals_W_2);
    -- end of group cjoin

    -- Instantiation of function
    Instance0 : processor_hcc_main
      port map (Call0_RE => globals_StartOut,
                globals_CForkIn_out => globals_CForkIn,
                globals_GND => globals_GND,
                globals_PWR => globals_PWR,
                globals_Receive => globals_Receive,
                globals_StartOut_out => globals_StartOut,
                globals_Transmit => globals_Transmit,
                globals_TrueZ_1_out => globals_TrueZ_1,
                globals_TrueZ_out => globals_TrueZ,
                globals_W_0 => globals_W_0,
                globals_W_1 => globals_W_1,
                globals_W_2_out => globals_W_2,
                globals_W_3_out => globals_W_3,
                globals_W_4_out => globals_W_4,
                globals_W_5_out => globals_W_5,
                globals_W_6_out => globals_W_6,
                globals_W_7 => globals_W_7,
                globals_acc_Out_out => globals_acc_Out,
                globals_clk => globals_clk_1,
                globals_clk_out => globals_clk,
                globals_pc_Out_out => globals_pc_Out,
                globals_rst => globals_rst,
                globals_value_Out_out => globals_value_Out,
                globals_value_read_Out_out => globals_value_read_Out
    );
    -- global connection
    globals_clk_out <= globals_clk;
    -- global connection
    globals_TrueZ_out <= globals_TrueZ;
    -- global connection
    globals_TrueZ_1_out <= globals_TrueZ_1;
    -- global connection
    globals_CForkIn_out <= globals_CForkIn;
    -- global connection
    globals_value_read_Out_out <= globals_value_read_Out;
    -- global connection
    globals_value_Out_out <= globals_value_Out;
  -- end of root group


end;

-- handel-c function: 'main' from source file: 'C:\My_Designs_61\Samples_61\PROCESSOR_DK\processor.hcc'
architecture behaviour of processor_hcc_main is
  -- External component declaration
  component div_rem
  port (
    a : in std_logic_vector(7 downto 0);
    b : in std_logic_vector(7 downto 0);
    clk : in std_logic;
    done : out std_logic;
    quot : out std_logic_vector(3 downto 0);
    remain : out std_logic_vector(3 downto 0);
    rst : in std_logic;
    start : in std_logic
  );
  end component;

  -- Input RE connection
  signal W_0 : unsigned(0 downto 0);
  -- Bitwise OR
  signal W_1 : unsigned(0 downto 0);
  -- Clock cycle delay
  signal globals_W_2 : unsigned(0 downto 0);
  -- Conditional true branch
  signal TrueZ : unsigned(0 downto 0);
  -- Conditional false branch
  signal FalseZ : unsigned(0 downto 0);
  -- Bitwise OR
  signal globals_W_3 : unsigned(0 downto 0);
  -- Clock cycle delay
  signal LoopZ : unsigned(0 downto 0);
  -- Conditional true branch
  signal TrueZ_1 : unsigned(0 downto 0);
  -- Conditional false branch
  signal FalseZ_1 : unsigned(0 downto 0);
  -- Bitwise OR
  signal W_2 : unsigned(0 downto 0);
  -- Clock cycle delay
  signal globals_W_4 : unsigned(0 downto 0);
  -- Clock cycle delay
  signal SeqChain : unsigned(0 downto 0);
  -- Conditional true branch
  signal globals_TrueZ : unsigned(0 downto 0);
  -- Conditional false branch
  signal FalseZ_2 : unsigned(0 downto 0);
  -- Bitwise OR
  signal globals_W_5 : unsigned(0 downto 0);
  -- Clock cycle delay
  signal LoopZ_1 : unsigned(0 downto 0);
  -- Clock cycle delay
  signal SeqChain_1 : unsigned(0 downto 0);
  -- Conditional true branch
  signal globals_TrueZ_1 : unsigned(0 downto 0);
  -- Conditional false branch
  signal FalseZ_3 : unsigned(0 downto 0);
  -- Plus
  signal BinOpOut : unsigned(0 downto 0);
  -- Expression split
  signal W_3 : unsigned(0 downto 0);
  -- Expression split
  signal W_4 : unsigned(0 downto 0);
  -- Expression split
  signal W_5 : unsigned(0 downto 0);
  -- Bitwise OR
  signal globals_CForkIn : unsigned(0 downto 0);
  -- Bitwise AND
  signal LinkWire_14 : unsigned(0 downto 0);
  -- Constant value
  constant W_6 : unsigned(3 downto 0) := "1001";
  -- Bitwise AND
  signal LinkWire_13 : unsigned(0 downto 0);
  -- Constant value
  constant W_7 : unsigned(3 downto 0) := "1000";
  -- Bitwise AND
  signal LinkWire_12 : unsigned(0 downto 0);
  -- Constant value
  constant W_8 : unsigned(3 downto 0) := "0111";
  -- Bitwise AND
  signal LinkWire_11 : unsigned(0 downto 0);
  -- Constant value
  constant W_9 : unsigned(3 downto 0) := "0110";
  -- Bitwise AND
  signal LinkWire_10 : unsigned(0 downto 0);
  -- Constant value
  constant W_10 : unsigned(3 downto 0) := "0101";
  -- Bitwise AND
  signal LinkWire_9 : unsigned(0 downto 0);
  -- Constant value
  constant W_11 : unsigned(3 downto 0) := "1101";
  -- Bitwise AND
  signal LinkWire_8 : unsigned(0 downto 0);
  -- Constant value
  constant W_12 : unsigned(3 downto 0) := "1100";
  -- Bitwise AND
  signal LinkWire_7 : unsigned(0 downto 0);
  -- Constant value
  constant W_13 : unsigned(3 downto 0) := "1110";
  -- Bitwise AND
  signal LinkWire_6 : unsigned(0 downto 0);
  -- Constant value
  constant W_14 : unsigned(3 downto 0) := "1010";
  -- Bitwise AND
  signal LinkWire_5 : unsigned(0 downto 0);
  -- Constant value
  constant W_15 : unsigned(3 downto 0) := "1111";
  -- Bitwise AND
  signal LinkWire_4 : unsigned(0 downto 0);
  -- Constant value
  constant W_16 : unsigned(3 downto 0) := "0100";
  -- Bitwise AND
  signal LinkWire_3 : unsigned(0 downto 0);
  -- Constant value
  constant W_17 : unsigned(3 downto 0) := "0011";
  -- Bitwise AND
  signal LinkWire_2 : unsigned(0 downto 0);
  -- Constant value
  constant W_18 : unsigned(3 downto 0) := "0010";
  -- Bitwise AND
  signal LinkWire_1 : unsigned(0 downto 0);
  -- Constant value
  constant W_19 : unsigned(3 downto 0) := "0001";
  -- Bitwise AND
  signal LinkWire_0 : unsigned(0 downto 0);
  -- Clock cycle delay
  signal SeqChain_2 : unsigned(0 downto 0);
  -- Clock cycle delay
  signal SeqChain_3 : unsigned(0 downto 0);
  -- Clock cycle delay
  signal SeqChain_4 : unsigned(0 downto 0);
  -- Clock cycle delay
  signal SeqChain_5 : unsigned(0 downto 0);
  -- Clock cycle delay
  signal SeqChain_6 : unsigned(0 downto 0);
  -- Clock cycle delay
  signal SeqChain_7 : unsigned(0 downto 0);
  -- Clock cycle delay
  signal SeqChain_8 : unsigned(0 downto 0);
  -- Clock cycle delay
  signal SeqChain_9 : unsigned(0 downto 0);
  -- Clock cycle delay
  signal SeqChain_10 : unsigned(0 downto 0);
  -- Clock cycle delay
  signal SeqChain_11 : unsigned(0 downto 0);
  -- Clock cycle delay
  signal SeqChain_12 : unsigned(0 downto 0);
  -- Clock cycle delay
  signal SeqChain_13 : unsigned(0 downto 0);
  -- Bitwise OR
  signal globals_W_6 : unsigned(0 downto 0);
  -- Clock cycle delay
  signal LoopZ_2 : unsigned(0 downto 0);
  -- Clock cycle delay
  signal SeqChain_14 : unsigned(0 downto 0);
  -- Conditional true branch
  signal TrueZ_2 : unsigned(0 downto 0);
  -- Conditional false branch
  signal FalseZ_4 : unsigned(0 downto 0);
  -- Bitwise OR
  signal W_20 : unsigned(0 downto 0);
  -- Clock cycle delay
  signal LoopZ_3 : unsigned(0 downto 0);
  -- Clock cycle delay
  signal SeqChain_15 : unsigned(0 downto 0);
  -- Conditional true branch
  signal TrueZ_3 : unsigned(0 downto 0);
  -- Conditional false branch
  signal FalseZ_5 : unsigned(0 downto 0);
  -- Clock cycle delay
  signal ThenDone : unsigned(0 downto 0);
  -- Take LSBs
  signal BinOpOut_1 : unsigned(4 downto 0);
  -- Drop LSBs
  signal BinOpOut_2 : unsigned(4 downto 0);
  -- Conditional true branch
  signal TrueZ_4 : unsigned(0 downto 0);
  -- Conditional false branch
  signal FalseZ_6 : unsigned(0 downto 0);
  -- Test for inequality
  signal BinOpOut_3 : unsigned(0 downto 0);
  -- Constant value
  constant ConstOut : unsigned(7 downto 0) := "00000000";
  -- Clock cycle delay
  signal SeqChain_16 : unsigned(0 downto 0);
  -- Bitwise OR
  signal W_21 : unsigned(0 downto 0);
  -- Conditional true branch
  signal TrueZ_5 : unsigned(0 downto 0);
  -- Conditional false branch
  signal FalseZ_7 : unsigned(0 downto 0);
  -- Test for inequality
  signal BinOpOut_4 : unsigned(0 downto 0);
  -- Clock cycle delay
  signal Z_Dones_1 : unsigned(0 downto 0);
  -- Concatenation of bits
  signal BinOpOut_5 : unsigned(7 downto 0);
  -- Concatenation of bits
  signal BinOpOut_6 : unsigned(7 downto 0);
  -- Minus
  signal BinOpOut_7 : unsigned(7 downto 0);
  -- Take LSBs
  signal BinOpOut_8 : unsigned(3 downto 0);
  -- Concatenation of bits
  signal BinOpOut_9 : unsigned(7 downto 0);
  -- Constant value
  constant ConstOut_1 : unsigned(6 downto 0) := "0000000";
  -- Minus
  signal BinOpOut_10 : unsigned(7 downto 0);
  -- Constant value
  constant ConstOut_2 : unsigned(7 downto 0) := "00000001";
  -- Plus
  signal BinOpOut_11 : unsigned(7 downto 0);
  -- Take LSBs
  signal BinOpOut_12 : unsigned(3 downto 0);
  -- Drop LSBs
  signal BinOpOut_13 : unsigned(4 downto 0);
  -- Concatenation of bits
  signal BinOpOut_14 : unsigned(7 downto 0);
  -- Constant value
  constant ConstOut_3 : unsigned(2 downto 0) := "000";
  -- Take LSBs
  signal BinOpOut_15 : unsigned(3 downto 0);
  -- Clock cycle delay
  signal Z_Dones_1_1 : unsigned(0 downto 0);
  -- Bitwise OR
  signal W_22 : unsigned(0 downto 0);
  -- Plus
  signal BinOpOut_16 : unsigned(4 downto 0);
  -- Constant value
  constant ConstOut_4 : unsigned(4 downto 0) := "00001";
  -- Conditional true branch
  signal TrueZ_6 : unsigned(0 downto 0);
  -- Conditional false branch
  signal FalseZ_8 : unsigned(0 downto 0);
  -- Test for inequality
  signal BinOpOut_17 : unsigned(0 downto 0);
  -- Constant value
  constant ConstOut_5 : unsigned(3 downto 0) := "0000";
  -- Constant value
  constant ConstOut_6 : unsigned(4 downto 0) := "00000";
  -- Conditional true branch
  signal TrueZ_7 : unsigned(0 downto 0);
  -- Conditional false branch
  signal FalseZ_9 : unsigned(0 downto 0);
  -- Test for inequality
  signal BinOpOut_18 : unsigned(0 downto 0);
  -- Constant value
  constant ConstOut_7 : unsigned(0 downto 0) := "1";
  -- Port connection
  signal W_23 : std_logic;
  -- Port connection
  signal W_24 : std_logic_vector(3 downto 0);
  -- Port connection
  signal W_25 : std_logic_vector(3 downto 0);
  -- Register 'b_int'
  signal b_int_Out : unsigned(7 downto 0);
  -- Register 'acc'
  signal globals_acc_Out : unsigned(7 downto 0);
  -- Register 'ir'
  signal ir_Out : unsigned(8 downto 0);
  -- Register 'go'
  signal go_Out : unsigned(0 downto 0);
  -- Register 'pc'
  signal globals_pc_Out : unsigned(4 downto 0);
  -- RAM 'data'
  type RAM_data_type is array (15 downto 0) of unsigned(7 downto 0);
  signal RAM_data : RAM_data_type;
  -- RAM 'data' read address
  signal RAM_data_RdAddr : unsigned(3 downto 0);
  -- RAM 'data' output
  signal W_26 : unsigned(7 downto 0);
  -- Constant value
  constant ConstOut_8 : unsigned(0 downto 0) := "0";
  -- Register 'value_read'
  signal globals_value_read_Out : unsigned(0 downto 0);
  -- Register 'value'
  signal globals_value_Out : unsigned(7 downto 0);
  -- Start block
  signal W_27 : unsigned(0 downto 0);
  -- Not block
  signal W_28 : unsigned(0 downto 0);
  -- Start wire
  signal globals_StartOut : unsigned(0 downto 0);

begin

  -- root group
    -- group function main
      -- Not block
      W_28 <= LNOT(W_27);
      -- Update of register 'value_read'
      process(globals_clk, globals_rst) begin
        if (globals_rst='1') then
          globals_value_read_Out <= "0";
        else
          if rising_edge(globals_clk) then
            if (to_std_logic(SeqChain)='1') then
              globals_value_read_Out <= BinOpOut;
            elsif (to_std_logic(SeqChain_1)='1') then
              globals_value_read_Out <= BinOpOut;
            elsif (to_std_logic(W_0)='1') then
              globals_value_read_Out <= ConstOut_8;
            end if;
          end if;
        end if;
      end process;
      -- Update of register 'value'
      process(globals_clk, globals_rst) begin
        if (globals_rst='1') then
          globals_value_Out <= "00000000";
        else
          if rising_edge(globals_clk) then
            if (to_std_logic(TrueZ)='1') then
              globals_value_Out <= globals_W_1;
            elsif (to_std_logic(TrueZ_1)='1') then
              globals_value_Out <= globals_W_1;
            end if;
          end if;
        end if;
      end process;
      -- Update of start block
      process(globals_clk, globals_rst) begin
        if (globals_rst='1') then
          W_27 <= "0";
        else
          if rising_edge(globals_clk) then
            W_27 <= globals_PWR;
          end if;
        end if;
      end process;
      -- Update of delay block
      process(globals_clk, globals_rst) begin
        if (globals_rst='1') then
          globals_StartOut <= "0";
        else
          if rising_edge(globals_clk) then
            globals_StartOut <= W_28;
          end if;
        end if;
      end process;
    -- end of group function main

    -- group fnstart
      -- Input RE connection
      W_0 <= Call0_RE;
    -- end of group fnstart

    -- group seq
    -- end of group seq

    -- group par
    -- end of group par

    -- group seq
    -- end of group seq

    -- group chan recv
    -- end of group chan recv

    -- group recvsync
      -- Conditional true branch
      TrueZ <= LAND(globals_W_2, globals_W_6);
      -- Conditional false branch
      FalseZ <= LAND(globals_W_2, LNOT(globals_W_6));
    -- end of group recvsync

    -- group cjoin
      -- Bitwise OR
      W_1 <= LOR(TrueZ_1, FalseZ);
      -- Update of clock cycle delay
      process(globals_clk, globals_rst) begin
        if (globals_rst='1') then
          globals_W_2 <= "0";
        else
          if rising_edge(globals_clk) then
            globals_W_2 <= W_1;
          end if;
        end if;
      end process;
    -- end of group cjoin

    -- group chan recv
    -- end of group chan recv

    -- group recvsync
      -- Conditional true branch
      TrueZ_1 <= LAND(globals_W_3, globals_W_6);
      -- Conditional false branch
      FalseZ_1 <= LAND(globals_W_3, LNOT(globals_W_6));
    -- end of group recvsync

    -- group cjoin
      -- Bitwise OR
      globals_W_3 <= LOR(W_0, LoopZ);
    -- end of group cjoin

    -- group delay
      -- Update of clock cycle delay
      process(globals_clk, globals_rst) begin
        if (globals_rst='1') then
          LoopZ <= "0";
        else
          if rising_edge(globals_clk) then
            LoopZ <= FalseZ_1;
          end if;
        end if;
      end process;
    -- end of group delay

    -- group seq
      -- Plus
      BinOpOut <= PLUS(globals_value_read_Out, ConstOut_7);
    -- end of group seq

    -- group chan send
    -- end of group chan send

    -- group sendsync
      -- Conditional true branch
      globals_TrueZ <= LAND(globals_W_4, W_20);
      -- Conditional false branch
      FalseZ_2 <= LAND(globals_W_4, LNOT(W_20));
    -- end of group sendsync

    -- group cjoin
      -- Bitwise OR
      W_2 <= LOR(SeqChain_1, FalseZ_2);
      -- Update of clock cycle delay
      process(globals_clk, globals_rst) begin
        if (globals_rst='1') then
          globals_W_4 <= "0";
        else
          if rising_edge(globals_clk) then
            globals_W_4 <= W_2;
          end if;
        end if;
      end process;
    -- end of group cjoin

    -- group delay
      -- Update of clock cycle delay
      process(globals_clk, globals_rst) begin
        if (globals_rst='1') then
          SeqChain <= "0";
        else
          if rising_edge(globals_clk) then
            SeqChain <= globals_TrueZ;
          end if;
        end if;
      end process;
    -- end of group delay

    -- group chan send
    -- end of group chan send

    -- group sendsync
      -- Conditional true branch
      globals_TrueZ_1 <= LAND(globals_W_5, W_20);
      -- Conditional false branch
      FalseZ_3 <= LAND(globals_W_5, LNOT(W_20));
    -- end of group sendsync

    -- group cjoin
      -- Bitwise OR
      globals_W_5 <= LOR(W_0, LoopZ_1);
    -- end of group cjoin

    -- group delay
      -- Update of clock cycle delay
      process(globals_clk, globals_rst) begin
        if (globals_rst='1') then
          LoopZ_1 <= "0";
        else
          if rising_edge(globals_clk) then
            LoopZ_1 <= FalseZ_3;
          end if;
        end if;
      end process;
    -- end of group delay

    -- group delay
      -- Update of clock cycle delay
      process(globals_clk, globals_rst) begin
        if (globals_rst='1') then
          SeqChain_1 <= "0";
        else
          if rising_edge(globals_clk) then
            SeqChain_1 <= globals_TrueZ_1;
          end if;
        end if;
      end process;
    -- end of group delay

    -- group seq
      -- RAM 'data' output
      W_26 <= RAM_data(to_integer(RAM_data_RdAddr));
      -- Update of register 'b_int'
      process(globals_clk, globals_rst) begin
        if (globals_rst='1') then
          b_int_Out <= "00000000";
        else
          if rising_edge(globals_clk) then
            if (to_std_logic(TrueZ_5)='1') then
              b_int_Out <= globals_acc_Out;
            elsif (to_std_logic(SeqChain_10)='1') then
              b_int_Out <= BinOpOut_5;
            end if;
          end if;
        end if;
      end process;
      -- Update of register 'acc'
      process(globals_clk, globals_rst) begin
        if (globals_rst='1') then
          globals_acc_Out <= "00000000";
        else
          if rising_edge(globals_clk) then
            if (to_std_logic(TrueZ_3)='1') then
              globals_acc_Out <= globals_W_0;
            elsif (to_std_logic(LinkWire_10)='1') then
              globals_acc_Out <= BinOpOut_7;
            elsif (to_std_logic(LinkWire_9)='1') then
              globals_acc_Out <= BinOpOut_9;
            elsif (to_std_logic(FalseZ_7)='1') then
              globals_acc_Out <= b_int_Out;
            elsif (to_std_logic(SeqChain_10)='1') then
              globals_acc_Out <= BinOpOut_6;
            elsif (to_std_logic(LinkWire_5)='1') then
              globals_acc_Out <= BinOpOut_10;
            elsif (to_std_logic(LinkWire_4)='1') then
              globals_acc_Out <= BinOpOut_11;
            elsif (to_std_logic(LinkWire_2)='1') then
              globals_acc_Out <= BinOpOut_14;
            elsif (to_std_logic(LinkWire_1)='1') then
              globals_acc_Out <= W_26;
            end if;
          end if;
        end if;
      end process;
      -- Update of register 'ir'
      process(globals_clk, globals_rst) begin
        if (globals_rst='1') then
          ir_Out <= "000000000";
        else
          if rising_edge(globals_clk) then
            if (to_std_logic(globals_CForkIn)='1') then
              ir_Out <= globals_W_7;
            end if;
          end if;
        end if;
      end process;
      -- Update of register 'go'
      process(globals_clk, globals_rst) begin
        if (globals_rst='1') then
          go_Out <= "0";
        else
          if rising_edge(globals_clk) then
            if (to_std_logic(SeqChain_8)='1') then
              go_Out <= ConstOut_8;
            elsif (to_std_logic(LinkWire_6)='1') then
              go_Out <= ConstOut_7;
            end if;
          end if;
        end if;
      end process;
      -- Update of register 'pc'
      process(globals_clk, globals_rst) begin
        if (globals_rst='1') then
          globals_pc_Out <= "00000";
        else
          if rising_edge(globals_clk) then
            if (to_std_logic(TrueZ_4)='1') then
              globals_pc_Out <= BinOpOut_1;
            elsif (to_std_logic(LinkWire_11)='1') then
              globals_pc_Out <= BinOpOut_1;
            elsif (to_std_logic(TrueZ_6)='1') then
              globals_pc_Out <= BinOpOut_16;
            elsif (to_std_logic(TrueZ_7)='1') then
              globals_pc_Out <= ConstOut_6;
            end if;
          end if;
        end if;
      end process;
      -- RAM 'data' read address multiplexer
      process(LinkWire_1, BinOpOut_8, LinkWire_4, LinkWire_10) begin
        if (to_std_logic(LinkWire_1)='1') then
          RAM_data_RdAddr <= BinOpOut_8;
        elsif (to_std_logic(LinkWire_4)='1') then
          RAM_data_RdAddr <= BinOpOut_8;
        elsif (to_std_logic(LinkWire_10)='1') then
          RAM_data_RdAddr <= BinOpOut_8;
        else
          RAM_data_RdAddr <= "0000";
        end if;
      end process;
      -- Update of RAM 'data'
      process(globals_clk) begin
        if rising_edge(globals_clk) then
          if (to_std_logic(LinkWire_3)='1') then
            RAM_data(to_integer(BinOpOut_12)) <= globals_acc_Out;
          end if;
        end if;
      end process;
      -- External component instance 'divider'
      Instance0 : div_rem
        port map (a => to_std_logic(globals_acc_Out),
                  b => to_std_logic(b_int_Out),
                  clk => globals_clk,
                  done => W_23,
                  quot => W_24,
                  remain => W_25,
                  rst => globals_rst,
                  start => to_std_logic(go_Out)
      );
    -- end of group seq

    -- group seq
    -- end of group seq

    -- group while
    -- end of group while

    -- group cjoin
      -- Expression split
      W_3 <= LOR(SeqChain_14, W_0);
      -- Expression split
      W_4 <= LOR(SeqChain_12, LOR(SeqChain_13, LOR(FalseZ_6, LOR(ThenDone, LOR(SeqChain_15, W_3)))));
      -- Expression split
      W_5 <= LOR(SeqChain_7, LOR(SeqChain_9, LOR(Z_Dones_1, LOR(SeqChain_16, LOR(SeqChain_11, W_4)))));
      -- Bitwise OR
      globals_CForkIn <= LOR(SeqChain_2, LOR(SeqChain_3, LOR(SeqChain_4, LOR(SeqChain_5, LOR(SeqChain_6, W_5)))));
    -- end of group cjoin

    -- group seq
    -- end of group seq

    -- group switch
      -- Take LSBs
      BinOpOut_15 <= ir_Out(3 downto 0);
    -- end of group switch

    -- group switch
      -- Bitwise AND
      LinkWire_14 <= LAND(
                          to_unsigned(EQ(W_6, BinOpOut_15)), 
                          Z_Dones_1_1);
      -- Bitwise AND
      LinkWire_13 <= LAND(
                          to_unsigned(EQ(W_7, BinOpOut_15)), 
                          Z_Dones_1_1);
      -- Bitwise AND
      LinkWire_12 <= LAND(
                          to_unsigned(EQ(W_8, BinOpOut_15)), 
                          Z_Dones_1_1);
      -- Bitwise AND
      LinkWire_11 <= LAND(
                          to_unsigned(EQ(W_9, BinOpOut_15)), 
                          Z_Dones_1_1);
      -- Bitwise AND
      LinkWire_10 <= LAND(
                          to_unsigned(EQ(W_10, BinOpOut_15)), 
                          Z_Dones_1_1);
      -- Bitwise AND
      LinkWire_9 <= LAND(
                         to_unsigned(EQ(W_11, BinOpOut_15)), 
                         Z_Dones_1_1);
      -- Bitwise AND
      LinkWire_8 <= LAND(
                         to_unsigned(EQ(W_12, BinOpOut_15)), 
                         Z_Dones_1_1);
      -- Bitwise AND
      LinkWire_7 <= LAND(
                         to_unsigned(EQ(W_13, BinOpOut_15)), 
                         Z_Dones_1_1);
      -- Bitwise AND
      LinkWire_6 <= LAND(
                         to_unsigned(EQ(W_14, BinOpOut_15)), 
                         Z_Dones_1_1);
      -- Bitwise AND
      LinkWire_5 <= LAND(
                         to_unsigned(EQ(W_15, BinOpOut_15)), 
                         Z_Dones_1_1);
      -- Bitwise AND
      LinkWire_4 <= LAND(
                         to_unsigned(EQ(W_16, BinOpOut_15)), 
                         Z_Dones_1_1);
      -- Bitwise AND
      LinkWire_3 <= LAND(
                         to_unsigned(EQ(W_17, BinOpOut_15)), 
                         Z_Dones_1_1);
      -- Bitwise AND
      LinkWire_2 <= LAND(
                         to_unsigned(EQ(W_18, BinOpOut_15)), 
                         Z_Dones_1_1);
      -- Bitwise AND
      LinkWire_1 <= LAND(
                         to_unsigned(EQ(W_19, BinOpOut_15)), 
                         Z_Dones_1_1);
      -- Bitwise AND
      LinkWire_0 <= LAND(
                         to_unsigned(EQ(ConstOut_5, BinOpOut_15)), 
                         Z_Dones_1_1);
    -- end of group switch

    -- group seq
      -- Minus
      BinOpOut_7 <= MINUS(globals_acc_Out, W_26);
      -- Take LSBs
      BinOpOut_8 <= BinOpOut_2(3 downto 0);
      -- Concatenation of bits
      BinOpOut_9 <= ConstOut_1 & to_unsigned(W_23);
      -- Minus
      BinOpOut_10 <= MINUS(globals_acc_Out, ConstOut_2);
      -- Plus
      BinOpOut_11 <= PLUS(globals_acc_Out, W_26);
      -- Take LSBs
      BinOpOut_12 <= BinOpOut_13(3 downto 0);
      -- Drop LSBs
      BinOpOut_13 <= ir_Out(8 downto 4);
      -- Concatenation of bits
      BinOpOut_14 <= ConstOut_3 & BinOpOut_2;
    -- end of group seq

    -- group delay
      -- Update of clock cycle delay
      process(globals_clk, globals_rst) begin
        if (globals_rst='1') then
          SeqChain_2 <= "0";
        else
          if rising_edge(globals_clk) then
            SeqChain_2 <= LinkWire_0;
          end if;
        end if;
      end process;
    -- end of group delay

    -- group delay
      -- Update of clock cycle delay
      process(globals_clk, globals_rst) begin
        if (globals_rst='1') then
          SeqChain_3 <= "0";
        else
          if rising_edge(globals_clk) then
            SeqChain_3 <= LinkWire_1;
          end if;
        end if;
      end process;
    -- end of group delay

    -- group delay
      -- Update of clock cycle delay
      process(globals_clk, globals_rst) begin
        if (globals_rst='1') then
          SeqChain_4 <= "0";
        else
          if rising_edge(globals_clk) then
            SeqChain_4 <= LinkWire_2;
          end if;
        end if;
      end process;
    -- end of group delay

    -- group delay
      -- Update of clock cycle delay
      process(globals_clk, globals_rst) begin
        if (globals_rst='1') then
          SeqChain_5 <= "0";
        else
          if rising_edge(globals_clk) then
            SeqChain_5 <= LinkWire_3;
          end if;
        end if;
      end process;
    -- end of group delay

    -- group delay
      -- Update of clock cycle delay
      process(globals_clk, globals_rst) begin
        if (globals_rst='1') then
          SeqChain_6 <= "0";
        else
          if rising_edge(globals_clk) then
            SeqChain_6 <= LinkWire_4;
          end if;
        end if;
      end process;
    -- end of group delay

    -- group delay
      -- Update of clock cycle delay
      process(globals_clk, globals_rst) begin
        if (globals_rst='1') then
          SeqChain_7 <= "0";
        else
          if rising_edge(globals_clk) then
            SeqChain_7 <= LinkWire_5;
          end if;
        end if;
      end process;
    -- end of group delay

    -- group delay
      -- Update of clock cycle delay
      process(globals_clk, globals_rst) begin
        if (globals_rst='1') then
          SeqChain_8 <= "0";
        else
          if rising_edge(globals_clk) then
            SeqChain_8 <= LinkWire_6;
          end if;
        end if;
      end process;
    -- end of group delay

    -- group delay
      -- Update of clock cycle delay
      process(globals_clk, globals_rst) begin
        if (globals_rst='1') then
          SeqChain_9 <= "0";
        else
          if rising_edge(globals_clk) then
            SeqChain_9 <= SeqChain_8;
          end if;
        end if;
      end process;
    -- end of group delay

    -- group delay
      -- Update of clock cycle delay
      process(globals_clk, globals_rst) begin
        if (globals_rst='1') then
          SeqChain_10 <= "0";
        else
          if rising_edge(globals_clk) then
            SeqChain_10 <= LinkWire_7;
          end if;
        end if;
      end process;
    -- end of group delay

    -- group delay
      -- Update of clock cycle delay
      process(globals_clk, globals_rst) begin
        if (globals_rst='1') then
          SeqChain_11 <= "0";
        else
          if rising_edge(globals_clk) then
            SeqChain_11 <= LinkWire_9;
          end if;
        end if;
      end process;
    -- end of group delay

    -- group delay
      -- Update of clock cycle delay
      process(globals_clk, globals_rst) begin
        if (globals_rst='1') then
          SeqChain_12 <= "0";
        else
          if rising_edge(globals_clk) then
            SeqChain_12 <= LinkWire_10;
          end if;
        end if;
      end process;
    -- end of group delay

    -- group delay
      -- Update of clock cycle delay
      process(globals_clk, globals_rst) begin
        if (globals_rst='1') then
          SeqChain_13 <= "0";
        else
          if rising_edge(globals_clk) then
            SeqChain_13 <= LinkWire_11;
          end if;
        end if;
      end process;
    -- end of group delay

    -- group chan send
    -- end of group chan send

    -- group sendsync
      -- Conditional true branch
      TrueZ_2 <= LAND(globals_W_6, globals_Receive);
      -- Conditional false branch
      FalseZ_4 <= LAND(globals_W_6, LNOT(globals_Receive));
    -- end of group sendsync

    -- group cjoin
      -- Bitwise OR
      globals_W_6 <= LOR(LinkWire_14, LoopZ_2);
    -- end of group cjoin

    -- group delay
      -- Update of clock cycle delay
      process(globals_clk, globals_rst) begin
        if (globals_rst='1') then
          LoopZ_2 <= "0";
        else
          if rising_edge(globals_clk) then
            LoopZ_2 <= FalseZ_4;
          end if;
        end if;
      end process;
    -- end of group delay

    -- group delay
      -- Update of clock cycle delay
      process(globals_clk, globals_rst) begin
        if (globals_rst='1') then
          SeqChain_14 <= "0";
        else
          if rising_edge(globals_clk) then
            SeqChain_14 <= TrueZ_2;
          end if;
        end if;
      end process;
    -- end of group delay

    -- group chan recv
    -- end of group chan recv

    -- group recvsync
      -- Conditional true branch
      TrueZ_3 <= LAND(W_20, globals_Transmit);
      -- Conditional false branch
      FalseZ_5 <= LAND(W_20, LNOT(globals_Transmit));
    -- end of group recvsync

    -- group cjoin
      -- Bitwise OR
      W_20 <= LOR(LinkWire_13, LoopZ_3);
    -- end of group cjoin

    -- group delay
      -- Update of clock cycle delay
      process(globals_clk, globals_rst) begin
        if (globals_rst='1') then
          LoopZ_3 <= "0";
        else
          if rising_edge(globals_clk) then
            LoopZ_3 <= FalseZ_5;
          end if;
        end if;
      end process;
    -- end of group delay

    -- group delay
      -- Update of clock cycle delay
      process(globals_clk, globals_rst) begin
        if (globals_rst='1') then
          SeqChain_15 <= "0";
        else
          if rising_edge(globals_clk) then
            SeqChain_15 <= TrueZ_3;
          end if;
        end if;
      end process;
    -- end of group delay

    -- group if
      -- Take LSBs
      BinOpOut_1 <= BinOpOut_2(4 downto 0);
      -- Drop LSBs
      BinOpOut_2 <= ir_Out(8 downto 4);
      -- Conditional true branch
      TrueZ_4 <= LAND(LinkWire_12, BinOpOut_3);
      -- Conditional false branch
      FalseZ_6 <= LAND(LinkWire_12, LNOT(BinOpOut_3));
      -- Test for inequality
      BinOpOut_3 <= to_unsigned(NEQ(
                                    to_unsigned(NEQ(globals_acc_Out, ConstOut)), 
                                    ConstOut_8));
    -- end of group if

    -- group delay
      -- Update of clock cycle delay
      process(globals_clk, globals_rst) begin
        if (globals_rst='1') then
          ThenDone <= "0";
        else
          if rising_edge(globals_clk) then
            ThenDone <= TrueZ_4;
          end if;
        end if;
      end process;
    -- end of group delay

    -- group if
      -- Conditional true branch
      TrueZ_5 <= LAND(LinkWire_8, BinOpOut_4);
      -- Conditional false branch
      FalseZ_7 <= LAND(LinkWire_8, LNOT(BinOpOut_4));
      -- Test for inequality
      BinOpOut_4 <= to_unsigned(NEQ(BinOpOut_2, ConstOut_6));
    -- end of group if

    -- group delay
      -- Update of clock cycle delay
      process(globals_clk, globals_rst) begin
        if (globals_rst='1') then
          SeqChain_16 <= "0";
        else
          if rising_edge(globals_clk) then
            SeqChain_16 <= W_21;
          end if;
        end if;
      end process;
    -- end of group delay

    -- group cjoin
      -- Bitwise OR
      W_21 <= LOR(TrueZ_5, FalseZ_7);
    -- end of group cjoin

    -- group par
      -- Concatenation of bits
      BinOpOut_5 <= ConstOut_5 & to_unsigned(W_25);
      -- Concatenation of bits
      BinOpOut_6 <= ConstOut_5 & to_unsigned(W_24);
    -- end of group par

    -- group delay
      -- Update of clock cycle delay
      process(globals_clk, globals_rst) begin
        if (globals_rst='1') then
          Z_Dones_1 <= "0";
        else
          if rising_edge(globals_clk) then
            Z_Dones_1 <= SeqChain_10;
          end if;
        end if;
      end process;
    -- end of group delay

    -- group par
    -- end of group par

    -- group if
      -- Conditional true branch
      TrueZ_7 <= LAND(globals_CForkIn, BinOpOut_18);
      -- Conditional false branch
      FalseZ_9 <= LAND(globals_CForkIn, LNOT(BinOpOut_18));
      -- Test for inequality
      BinOpOut_18 <= to_unsigned(NEQ(to_unsigned(globals_rst), ConstOut_8));
    -- end of group if

    -- group delay
      -- Update of clock cycle delay
      process(globals_clk, globals_rst) begin
        if (globals_rst='1') then
          Z_Dones_1_1 <= "0";
        else
          if rising_edge(globals_clk) then
            Z_Dones_1_1 <= W_22;
          end if;
        end if;
      end process;
    -- end of group delay

    -- group cjoin
      -- Bitwise OR
      W_22 <= LOR(TrueZ_7, LOR(FalseZ_8, TrueZ_6));
    -- end of group cjoin

    -- group if
      -- Plus
      BinOpOut_16 <= PLUS(globals_pc_Out, ConstOut_4);
      -- Conditional true branch
      TrueZ_6 <= LAND(FalseZ_9, BinOpOut_17);
      -- Conditional false branch
      FalseZ_8 <= LAND(FalseZ_9, LNOT(BinOpOut_17));
      -- Test for inequality
      BinOpOut_17 <= to_unsigned(NEQ(
                                     to_unsigned(NEQ(BinOpOut_15, ConstOut_5)), 
                                     ConstOut_8));
    -- end of group if

    -- Input clock connection
    globals_clk_out <= globals_clk;
    -- Clock cycle delay
    globals_W_2_out <= globals_W_2;
    -- Bitwise OR
    globals_W_3_out <= globals_W_3;
    -- Clock cycle delay
    globals_W_4_out <= globals_W_4;
    -- Conditional true branch
    globals_TrueZ_out <= globals_TrueZ;
    -- Bitwise OR
    globals_W_5_out <= globals_W_5;
    -- Conditional true branch
    globals_TrueZ_1_out <= globals_TrueZ_1;
    -- Bitwise OR
    globals_CForkIn_out <= globals_CForkIn;
    -- Bitwise OR
    globals_W_6_out <= globals_W_6;
    -- Register 'acc'
    globals_acc_Out_out <= globals_acc_Out;
    -- Register 'pc'
    globals_pc_Out_out <= globals_pc_Out;
    -- Register 'value_read'
    globals_value_read_Out_out <= globals_value_read_Out;
    -- Register 'value'
    globals_value_Out_out <= globals_value_Out;
    -- Start wire
    globals_StartOut_out <= globals_StartOut;
  -- end of root group


end;

